### ISSUE TITLE
Cant pull submodule WebDriver

### ISSUE THREAD

**Issue by extr3mal** [appium/appium-xcuitest-driver#1]
#appium-xcuitest-driver user$ git submodule init
Submodule 'WebDriverAgent' (git@github.com:appium/WebDriverAgent.git) registered for path 'WebDriverAgent'
#appium-xcuitest-driver user$ git submodule update
Cloning into 'WebDriverAgent'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:appium/WebDriverAgent.git' into submodule path 'WebDriverAgent' failed

**Comment by Jonahss** [comment]
The submodule uses the ssh url for github not https. You should have ssh for github set up?

**Comment by prolificcoder** [comment]
I have the same problem. I currently do not have any ssh setup for public github

**Comment by imurchie** [comment]
This is now https.
