### ISSUE TITLE
Do we need to signature webdriveragent by using appium-xcuitest-driver?

### ISSUE THREAD

**Issue by caizhenxing** [appium/appium-xcuitest-driver#106]
Hi all,
when i run testing with appium-xcuitest-driver, i get the following error:

**The following build commands failed:
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/KissXML.framework
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/Peertalk.framework
(3 failures)

>> xctest-client.js:163:14 [master] pid:3200 xctest client exit with code: 65, signal: null**

anyone can help me? thanks

**Comment by imurchie** [comment]
@yaphatak might know better. But real device support is a work in progress awaiting a major bit of code to get in.

**Comment by caizhenxing** [comment]
@yaphatak could you help me?

**Comment by yaphatak** [comment]
![wdaxcodeeditor](https://cloud.githubusercontent.com/assets/12143988/18036963/c3ff2972-6d2d-11e6-9998-29c6c76131bd.png)
WDA xcode editor should look like this. WDA needs to be signed for real devices

**Comment by caizhenxing** [comment]
@yaphatak Got it, thx for your reply
