### ISSUE TITLE
Can't click/tap on keyboard search button when device in landscape mode

### ISSUE THREAD

**Issue by wfanforever** [appium/appium-xcuitest-driver#107]
Im not sure if this is a known issue, but noticed that when I have my iPad air 2 sim on landscape mode, the click action doesn't work. It works when it in portrait mode. 

From the log, it got the element, and http request returns 200. 
```
info MJSONWP Responding to client with driver.findElementFromElement() result: {"ELEMENT":"CE6A1DDF-A33F-4...
info HTTP <-- POST /wd/hub/session/25fc9526-7037-44c1-a3ab-7950ef4864e4/element/E6245DA3-67AB-4A84-BBD5-5D18316F5937/element 200 620 ms - 170 
info HTTP --> POST /wd/hub/session/25fc9526-7037-44c1-a3ab-7950ef4864e4/element/CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454/click {"id":"CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454"}
info MJSONWP Driver proxy active, passing request on via HTTP proxy
info JSONWP Proxy Proxying [POST /wd/hub/session/25fc9526-7037-44c1-a3ab-7950ef4864e4/element/CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454/click] to [POST http://localhost:8100/session/D5541FA5-EC31-4EBB-9464-9E7E7DD60688/element/CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454/click] with body: {"id":"CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454"}
info JSONWP Proxy Got response with status 200: {"status":0,"id":"CE6A1DDF-...
info JSONWP Proxy Replacing sessionId D5541FA5-EC31-4EBB-9464-9E7E7DD60688 with 25fc9526-7037-44c1-a3ab-7950ef4864e4
info HTTP <-- POST /wd/hub/session/25fc9526-7037-44c1-a3ab-7950ef4864e4/element/CE6A1DDF-A33F-4191-9FEC-E41B6CD2F454/click 200 774 ms - 118 
```

**Comment by wfanforever** [comment]
There's another issue probably not 100% related but also happened when you have device on landscape mode. So the app background/foreground failed when I tried this one.

https://github.com/facebook/WebDriverAgent/wiki/Queries#deactivate-application-for-given-time

```
{
  "value" : "Error Domain=com.facebook.WebDriverAgent Code=1 \"Timeout waiting for application to activate\" UserInfo={NSLocalizedDescription=Timeout waiting for application to activate}",
  "sessionId" : "FA0B749F-40A9-434A-B44D-77F04846FB01",
  "status" : 13
}
```

**Comment by imurchie** [comment]
I think we need more information. I just ran our entire test suite against a device in landscape mode.

Is it possible that the elements that you are trying to click are not on the screen, though they are findable?

**Comment by wfanforever** [comment]
I think a good example could be try to click the search button here. 

The search button is on the screen, but when you run the click curl script, it doesnt click on the button.

<img width="758" alt="search" src="https://cloud.githubusercontent.com/assets/21108234/18013951/7d08a5a2-6b75-11e6-8341-cac934df074c.png">

**Comment by imurchie** [comment]
What steps did you go through to get here? So I can reproduce.

**Comment by wfanforever** [comment]
Here're the steps, hope this would help, I followed the wiki here: https://github.com/facebook/WebDriverAgent/wiki/Queries#tapping-element

Device is on landscape mode: 
1. I launch the app, for example:  `curl -X POST '-H "Content-Type: application/json"' -d "{\"desiredCapabilities\":{\"bundleId\":\"com.facebook.IntegrationApp\"}}" http://localhost:8100/session`
2. Background the app, on the spotlight search I tried to get the search button element id: 
`curl -X POST '-H "Content-Type: application/json"' -d "{\"using\":\"predicate string\",\"value\":\" elementType == 9 and label == 'Search' \"}" http://localhost:8100/session/03303656-C5D9-4AAB-A0A6-D1802F733C4F/elements`
```
"value" : [
    {
      "ELEMENT" : "25421503-61B3-48A6-A39D-6670C87F1BAF",
      "type" : "XCUIElementTypeButton",
      "label" : "Search"
    }
  ],
  "sessionId" : "03303656-C5D9-4AAB-A0A6-D1802F733C4F",
  "status" : 0
```
3. Try to click on it using the curl `curl -X POST '-H "Content-Type: application/json"' -d "" http://localhost:8100/session/03303656-C5D9-4AAB-A0A6-D1802F733C4F/element/25421503-61B3-48A6-A39D-6670C87F1BAF/click`

**Comment by imurchie** [comment]
Pursuing this with [WebDriverAgent](https://github.com/facebook/WebDriverAgent) folks might be a better bet than here, since this doesn't seem to involve Appium at all.

**Comment by wfanforever** [comment]
Yeaa I realized when I described the steps. :(
