### ISSUE TITLE
WDA Performance 

### ISSUE THREAD

**Issue by 4ndrey** [appium/appium-xcuitest-driver#1129]
Hello guys,

I noticed strange performance issue with WDA running on iPhone 6s and iPhone 8 (ios 13.3 + latest WebDriverAgent). 

From my point of view UI tests on iPhone 8 should usually be quicker in comparison to iPhone 6. 

I wrote simple test which opens Settings app and verifies iOS version repeating this action 10 times. 
Execution times are almost the same, although iPhone 6s is slightly faster still. 

Then I added new action to rename Device Name using text field. And now iPhone 6s executes test way faster, depending on number of editing actions (iPhone 8 runs approx 1 sec longer per each edit action). 

Do you have any ideas or suggestions, why it is happening?

Thanks in advance!

**Comment by KazuCocoa** [comment]
As issue template addressed, please create the issue in https://github.com/appium/appium/issues/new with the full Appium log.
It is appreciated the log has `showXcodeLog: true` and `showIOSLog: true`. We can investigate if the cause is XCUITest framework itself or Appium can improve it.
