### ISSUE TITLE
Driver hangs waiting for WebDriverAgent when day of the month is a single digit

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium-xcuitest-driver#117]
If the day of the month is between 1 and 9, it is displayed in the log as a single digit, i.e. Sep  1 2016 (instead of Sep 01 2016).
The regex LOG_STARTTIME_REGEX in webdriveragent.js only checks if the for 2-digit days of the months, which causes the driver to hang.

**Comment by imurchie** [comment]
This ought to be fixed by #118.
