### ISSUE TITLE
alert.accept() returns NoSuchElementException instead of NoAlertPresentException

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium-xcuitest-driver#119]
When using appium with the java client, attempting to accept/dismiss an alert when there is no alert present should throw a NoAlertPresentException, but instead a NoSuchElementException is thrown.

It works properly with appium-ios-driver, so the bug is (probably) in appium-xcuitest-driver and not in the java client.

**Comment by imurchie** [comment]
This is in the native context?

**Comment by imurchie** [comment]
https://github.com/facebook/WebDriverAgent/pull/271

**Comment by imurchie** [comment]
WDA fix is in Appium. This should be fixed now.
