### ISSUE TITLE
Add WebDriverAgent touch id support to Appium

### ISSUE THREAD

**Issue by kaleposhobios** [appium/appium-xcuitest-driver#12]
I submitted a pull request to facebook/WebDriverAgent that includes support for sending Simulator Touch ID Match and NoMatch commands.

How do we want to include this into Appium? Just include it into core Appium as a route and then into each of the client libs? In theory there might be something comparable in the Android lib at some point, I'd think.

**Comment by Jonahss** [comment]
We can include it into [this package](https://github.com/appium/node-mobile-json-wire-protocol) which governs the api of all appium drivers. By default if a driver doesn't implement a route they automatically respond with a NotYetImplemented error.

Well Done!

**Comment by kaleposhobios** [comment]
Thanks. Once it gets pulled into facebook/WebDriverAgent I will submit a PR to appium/node-mobile-json-wire-protocol. 

Would we then also make tickets in each of the language drivers to add support for it? And, would we want to bring this same functionality into the current/primary appium iOS driver?

**Comment by Jonahss** [comment]
Yes, the next step is to add the command to all the individual language drivers.

I don't think it's worth adding to the current iOS driver, but we could if you really needed it.

**Comment by kaleposhobios** [comment]
Hi Jonah,

Thanks. I don't need it in the current iOS driver at all.

**Comment by kaleposhobios** [comment]
I have submitted a PR to appium/node-mobile-json-wire-protocol: https://github.com/appium/node-mobile-json-wire-protocol/pull/39

**Comment by kaleposhobios** [comment]
Hi Jonah,

Next question. I have made updates to each of the pieces in my forks (node-mobile-json-wire-protocol, python-client, appium-xcuitest-driver). But, I'm not actually sure how to switch the entire ecosystem over to using it. I'm not sure if I should just try to test each component and make the PRs? Or if I should try to set it up here so I can do the whole "end-to-end" test. Any thoughts?

**Comment by Jonahss** [comment]
Well let's merge the changes into this repo (appium-xcuitest-driver). I've been meaning to review them. I'll review them and we can merge here.
Then we can wait on the merge to node-mobile-json-wire-protocol. Looks good to me, just waiting on final confirmation from the project lead.

Then you can test using your fork of the python driver.

**Comment by kaleposhobios** [comment]
Ok, the node-mobile-son-wire-protocol changes were now made. I just realized, I don't think we need any specific code in this repository (appium-xcuitest-driver) at all. Because, since WebDriverAgent handles the route properly, we don't need to do anything here. Is that right?

If so, I think all we'll need to do is update this repository to point to the latest WebDriverAgent master (which has the support for the touch id commands), then once you do that I can try out the python-client changes I made. And if those work, I can make a PR there?

**Comment by Jonahss** [comment]
Whoo! yeah that's perfect.
The benefit of our proxy and node-mobile-json-wire-protocol architecture :)
I already included a newer WebDriverAgent that has the TouchId commands.

**Comment by kaleposhobios** [comment]
Hi Jonah,

When I try our Python branch, I confirm it's sending the command:
```info HTTP --> POST /wd/hub/session/e8c7d702-8cae-446c-b9bd-6fd55b3a25e2/simulator/touch_id```

But then in the logs we see this:
```dbug HTTP No route found. Setting content type to 'text/plain'```

Do you happen to have any ideas about this? The WDA submodule looks right so I'm wondering if there is some other appium project whose code I have to change to handle this new route?

**Comment by kaleposhobios** [comment]
Hi Jonah,

Sorry for falling off the face of the earth for a bit. Hopefully this work will still be useful -- Do you have any ideas about the above? This was one of the final steps for us getting this working. Thanks!

**Comment by rkavalap** [comment]
Closing this issue. 
https://github.com/appium/appium/issues/7013
