### ISSUE TITLE
curl: (7) Failed to connect to 10.180.26.224 port 8100: Operation timed out

### ISSUE THREAD

**Issue by xiaoduola666** [appium/appium-xcuitest-driver#1243]
**Warning:**

手动配置后，进行测试，一直超时是为什么呢
![image](https://user-images.githubusercontent.com/32089099/95648506-5810b300-0b0a-11eb-8c06-96e8a5a8e374.png)

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by KazuCocoa** [comment]
I did not know about your network environment, but I guess your device did not in the same network with Appium 

> To completely verify, you can try accessing the WebDriverAgent server status (note: you must be on the same network as the device, and know its IP address, from Settings => Wi-Fi => Current Network):

http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/
