### ISSUE TITLE
Clicking element results in test crashing

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#13]
Hey, Im kinda thinking this is a XCUITest bug, but wanted to know if any of you have ran into the same issue.

So when executing some commands on a iphone 6 v9.2 simulator, after one click that updates the nav menu of our app, all the element on the menu are still "visible and enabled" but when you try to click on of them, the driver takes awhile but then crashes, which in turns closes our app.

Now a weird things about it is if I manually intervene with the menu while the driver is trying to click, it will work. :/

There are now errors in the driver console. just this.
```
info MJSONWP Driver proxy active, passing request on via HTTP proxy
info JSONWP Proxy Proxying [GET /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/text] to [GET http://localhost:8100/session/2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57/element/41/text] with body: {}
info JSONWP Proxy Got response with status 200: "{\n  \"value\" : \"Mens Varsity Basketball\",\n  \"sessionId\" : \"2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57\",\n  \"status\" : 0\n}"
info JSONWP Proxy Replacing sessionId 2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57 with dd9836fc-d8c2-46c5-8cad-4ecd37c3020a
info HTTP <-- GET /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/text 200 54.734 ms - 97
info HTTP --> POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click
info MJSONWP Driver proxy active, passing request on via HTTP proxy
info JSONWP Proxy Proxying [POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click] to [POST http://localhost:8100/session/2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57/element/41/click] with body: {"id":41,"sessionId":"dd9836fc-d8c2-46c5-8cad-4ecd37c3020a"}
info JSONWP Proxy Got response with status 200: {"status":0,"id":41,"value":"","sessionId":"2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57"}
info JSONWP Proxy Replacing sessionId 2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57 with dd9836fc-d8c2-46c5-8cad-4ecd37c3020a
info HTTP <-- POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click 200 5848.169 ms - 82
info HTTP --> POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click
info MJSONWP Driver proxy active, passing request on via HTTP proxy
info JSONWP Proxy Proxying [POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click] to [POST http://localhost:8100/session/2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57/element/41/click] with body: {"id":41,"sessionId":"dd9836fc-d8c2-46c5-8cad-4ecd37c3020a"}
info JSONWP Proxy Got response with status 200: {"value":"Interrupting test","sessionId":"2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57","status":13}
info JSONWP Proxy Replacing sessionId 2F3EB064-15FA-4DE4-8FFA-37BF7B4FDA57 with dd9836fc-d8c2-46c5-8cad-4ecd37c3020a
info HTTP <-- POST /wd/hub/session/dd9836fc-d8c2-46c5-8cad-4ecd37c3020a/element/41/click 200 30246.698 ms - 92
info WebDriverAgent-driver xcodebuild exited with code 65 and signal null
```

**Comment by kaleposhobios** [comment]
Any chance you could use the debug instructions on the WebDriverAgent page (https://github.com/facebook/webdriveragent) and start WebDriverAgent yourself (either through command line or Xcode) and then trigger the same case via cURL? I suspect the WebDriverAgent output would be very helpful in this case.

**Comment by joshrlesch** [comment]
I tried, not sure if Im doing something wrong,

I started webdriveragent with:
`xcodebuild -workspace WebDriverAgent.xcworkspace -scheme XCTUITestRunner -destination id='53EB8B13-AC5C-4C00-B9A6-E420F04E2FFE' test`

once the blue screen was up and got the server address in the device logs

started a session with:
`curl -X POST -H "Content-Type: application/json" -d "{\"desiredCapabilities\":{\"bundleId\":\"com.app.example\", \"app\":\"/Users/jl/Library/Devloper/Xcode/DerivedData/Example-cjtrsczigiznjseugfepdeoohyvo/Build/Products/Debug-iphonesimulator/Examplel.app\"}}" http://10.103.16.38:8100/session/`

It actually installs the app and launches it, but then times out with. But it didn't crash.
```
{
  "sessionId" : "59D9C600-8D94-4795-B492-BFDABA63650B",
  "value" : "Application is not running, possibly crashed",
  "status" : 10
}
```

Am I missing a step?

**Comment by kaleposhobios** [comment]
That looks right to me. It looks like a typo in the app path though: ".../Library/Devloper/". I'm not sure if that's a typo in the curl command or not. Looking at webdriveragent code, it creates an instance of the XCTest "app" directly using the provided app path and bundle id: 
```
XCUIApplication *app = [[XCUIApplication alloc] initPrivateWithPath:appPath bundleID:bundleID];
```
I don't know if, if the path is invalid, if the app would be non-nil and therefore look like a valid session, but then fail with that error (which is, the ```app``` created is retuned by the system as not running).

But, that seems like the most likely culprit to me?

**Comment by joshrlesch** [comment]
Yeah that was a typo with my copy/paste. I tried it again but in xcode, can this is what is being returned in the xcode console.

```
 No application process found matching pid 75698, caching
2016-01-12 10:37:51.400 XCTStubApps[75692:8332009] Enqueue Failure: UI Testing Failure - App accessibility isn't loaded /Users/josh.lesch/Documents/github/WebDriverAgent/XCTWebDriverAgentLib/Commands/FBSessionCommands.m 37 1
2016-01-12 10:37:51.400 XCTStubApps[75692:8332009] Waiting for <XCUIApplicationImpl: 0x7f855b303a10> to be running-active
2016-01-12 10:38:21.403 XCTStubApps[75692:8332009] Enqueue Failure: UI Testing Failure - '<XCUIApplicationImpl: 0x7f855b303a10>' App state is still not running active, state = XCApplicationStateNotRunning /Users/josh.lesch/Documents/github/WebDriverAgent/XCTWebDriverAgentLib/Commands/FBSessionCommands.m 37 1
2016-01-12 10:38:21.462 XCTStubApps[75692:8332009] done launching and has quiesced
```

**Comment by kaleposhobios** [comment]
Hmmm. I don't want to waste your time debugging something that isn't directly related to your issue. I was hoping that by seeing the WebDriverAgent logs something might show that would be useful. The short answer is I haven't seen anything like your original question, but I don't know if it's an XCTest issue or WebDriverAgent issue (although if I had to make a relatively uneducated guess, I'd say a WebDriverAgent issue).

**Comment by joshrlesch** [comment]
I will keep messing around with this and see if I can get it to work, this is frustrating me, ha

**Comment by Jonahss** [comment]
I feel ya. The XCUITest stuff is really frustrating because Apple didn't seem to really finish it before releasing it. The log output from Xcode is really sketchy, even when running plain XCUITests right from Xcode :/

Anything you can figure out now will help a lot of poeple in the future, as we will have to migrate all appium users to this driver once Instruments is completely removed by Apple.

**Comment by joshrlesch** [comment]
I believe this may have been fixed with the latest release of xcode. I pull the latest bits for the appium-xcuitest-driver and ran tests against it and it is working as it should now. 

Going to close this issue.
