### ISSUE TITLE
"waitForIdleTimeout" is unavailable for IOS on animation view

### ISSUE THREAD

**Issue by taisiting** [appium/appium-xcuitest-driver#1325]
Appium version: v 1.21.0
Desktop OS/version used to run Appium: Mac: 11.1
Node.js version (unless using Appium.app|exe): 12.8.1
Mobile platform/version under test: IOS: 14.5
Real device: Iphone 12pro

For the info from https://github.com/appium/python-client/issues/621.

I use "driver.update_settings({"waitForIdleTimeout": 100})" which is the python client api for Appium, but it's  only valid on Android. 
For ios, it needs about 2 minutes to handle because the animation on the view is working.
I wonder how to solve it on my appium/python-client framework.

**Comment by KazuCocoa** [comment]
iOS is a bit different as below, but XCTest by Apple works on the main thread. Animation blocks the XCtest behavior, so Appium's hack to set the timeout zero may cause https://github.com/appium/appium/issues/15677#issuecomment-891738582

https://github.com/appium/appium-xcuitest-driver

> appium:waitForIdleTimeout
> The amount of time in float seconds to wait until the application under test is idling. XCTest requires the app's main thread to be idling in order to execute any action on it, so WDA might not even start/freeze if the app under test is constantly hogging the main thread. The default value is 10 (seconds). Setting it to zero disables idling checks completely (not recommended) and has the same effect as setting waitForQuiescence to false. Available since Appium 1.20.0.

**Comment by taisiting** [comment]
@KazuCocoa So this time-consuming problem still cannot be solved?

**Comment by KazuCocoa** [comment]
Afaik, yes, unfortunately. You could report it to Apple. Nothing can inject XCTest from Appium.
Or probably you could stop animation (the main thread) in the app once for testing by XCTest framework (Appium).

**Comment by taisiting** [comment]
How to  stop animation  in the app during testing with XCTest framework (Appium)? 
We have lots of test cases and this problem caused the long long runtime, my appreciate for any suggestion.

**Comment by KazuCocoa** [comment]
It depends on your app under test.
e.g. https://developer.apple.com/documentation/uikit/uiview/1622420-setanimationsenabled (but this might cause another issue which happens with no-animation case. Reducing processes on the main thread also may help.
