### ISSUE TITLE
setValue not working - WDA expects array of chars, not string

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium-xcuitest-driver#133]
When using setValue with a simple string (no special keys), the following errors occurs:
`An unknown server-side error occurred while processing the command. Original error: -[__NSCFString componentsJoinedByString:]: unrecognized selector sent to instance 0x146890d40`

This happens because element.js sends the value as a string, while WDA expects an array of chars (FBElementsCommands.m:154):
`NSString *textToType = [value componentsJoinedByString:@""];`

**Comment by imurchie** [comment]
Shoot. So intent on getting the special characters wrong. Fixing.

**Comment by imurchie** [comment]
Available in `appium-xcuitest-driver@2.0.13`
