### ISSUE TITLE
How do you actually use this?

### ISSUE THREAD

**Issue by krischik** [appium/appium-xcuitest-driver#1358]
I have read the documentation for setting up real device config for iOS:

https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

It's starts off with setting up developer ids but I'm at a loss as what the appium-xcuitest-driver is actually good for. Is this an application I need to install, a library I have to add to my add, a what?

The main README isn't much help either:

https://github.com/appium/appium-xcuitest-driver

Could you please start the README by explaining what this „driver“ is actually good for.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/16203
