### ISSUE TITLE
Application is not launching when Web driver Agent is running in device

### ISSUE THREAD

**Issue by bikeebh** [appium/appium-xcuitest-driver#1362]
There is one iOS dev App it's not launching when wda is running in the device it's getting crashed.

When we stop running wda in device and launch app it's started working properly 

We have changes the port number 8100  and 9100 still getting the same issue

Please help me if fixing this

**Comment by KazuCocoa** [comment]
Could you share the system log?

**Comment by boneskull** [comment]
Please reopen if still an issue.
