### ISSUE TITLE
Requesting mobileCommand for setKeys without element dependent

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-xcuitest-driver#1368]
Current sendKeys function requires element id and session id

but webdriveragent allows to send text without element dependent

can you please add this functionality as execution command.

reference: 
 
POST: {{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
BODY: {"value":["test"],"frequency":120}

**Comment by krishtoautomate** [comment]
can be it be extended to java and javascript also instead of limiting this action to ruby and python

**Comment by KazuCocoa** [comment]
They also should have

**Comment by krishtoautomate** [comment]
Any reasons why this function is not added to xcuitest driver

**Comment by KazuCocoa** [comment]
Since they https://github.com/appium/appium-xcuitest-driver/issues/1368#issuecomment-1014175145 supported the endpoint in MJSONWP as below, and the same behavior is in W3C actions's send_keys as we follow W3C WebDriver spec.
So, it seems this issue is to create a duplication method as mobile command.
https://github.com/appium/appium-xcuitest-driver/blob/31c83daf7fc06c7b9eae3ee840194cbb93cc42d1/lib/commands/element.js#L203-L207

**Comment by KazuCocoa** [comment]
As the above comment, this endpoint is used in MJSONWP(as send keys to an active element) and W3C's send_keys actions (as another endpoint, but the same behavior as WebDriver spec).

---

Probably https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#sendKeys(java.lang.CharSequence...) is W3C action's send_keys in Java.

https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html#sendKeys is in JavaScript one

**Comment by krishtoautomate** [comment]
Found it -

new TouchActions(driver).sendKeys("text") working in java. But not satisfying solution to use in javascript as i use xcuitest lib

**Comment by KazuCocoa** [comment]
> xcuitest lib

Sorry, what does this mean?
For webdriverio, probably you need to create a W3C action with https://appium.io/docs/en/commands/interactions/actions/ as the Java code issued. (you can see what json body was sent in the appium log)

**Comment by krishtoautomate** [comment]
Interaction works but not easy with sendKeys without elementId if only depending on xcuitestdriver
