### ISSUE TITLE
Initial Siri enablement takes 60 sec

### ISSUE THREAD

**Issue by DzmitryIlyin** [appium/appium-xcuitest-driver#1393]
I'm using java-client:8.0.0-beta2 and appium mac 1.22.2
When Siri is not enabled on real device this command driver.executeScript("mobile: siriCommand", args) takes 60 sec to execute, once enabled everything is fine. It seems to be some timeout, so maybe it's possible to control it somehow?

**Comment by KazuCocoa** [comment]
The siri behavior is expected.
You should enable it before XCTest process. Probably `activateWithVoiceRecognitionText` (XCTest API) to call the siri command waited for the timeout.
