### ISSUE TITLE
driver.getPageSource() - wrong tags in returned xml

### ISSUE THREAD

**Issue by arompa** [appium/appium-xcuitest-driver#142]
* **Appium Version:** 1.6.0-beta1 (with capability AutomationName XCUITest)
* **java-client:** 4.1.2

`driver.getPageSource()` returns xml with tags without prefix - e.g.: 
* `StaticText`
* `SegmentedControl`

When in reality the tags have `XCUIElementType` prefix - e.g.:
* `XCUIElementTypeStaticText`

Whereas `element.getTagName()` returns proper tag name (with prefix)

**Comment by imurchie** [comment]
Yes, the values returned in the source are stripped of `XCUIElementType`. This is done upstream. You should be able to use the bare name, or prepend `XCUIElementType`.

**Comment by arompa** [comment]
In theory yes, this should work with the bare name, because (if I am not mistaken) By.className looks for exact className first and if not found it looks for an element containing given string in className, but when looking for TextField or SecureTextField, you'll get unexpected results - e.g. username being entered into password field. 

When getPageSource() returns the stripped tags it's way harder to troubleshoot why this is happening - I had to find the element by other strategy and use getTagName() to find out about this prefix.

But these are just my observations. I am sure that you guys have it though out ;)

Thanks for the fast response!

Cheers,
Anna

**Comment by imurchie** [comment]
I am happy to add the prefix back on. I don't understand why the system strips them, really.

**Comment by midopa** [comment]
If this doesn't affect locators, then I'd rather have the prefix stripped. It makes locators in test code easier to read.

**Comment by christoff-1992** [comment]
That is true, I suppose we can locally make an edit based on #151 to exclude the prefix if needed.

**Comment by imurchie** [comment]
The [comment](https://github.com/appium/appium-xcuitest-driver/issues/142#issuecomment-247254056) above makes it seem that there are consequences.

**Comment by midopa** [comment]
Ah, missed that. OK, makes sense to me!
