### ISSUE TITLE
Capability ORIENTATION does not work

### ISSUE THREAD

**Issue by arompa** [appium/appium-xcuitest-driver#143]
* **Appium Version:** 1.6.0-beta1 (with capability AutomationName XCUITest)
* **java-client:** 4.1.2

`capabilities.setCapability(MobileCapabilityType.ORIENTATION, ScreenOrientation.LANDSCAPE);`
 does not work - the device (simulator) is not rotated from portrait to landscape.

Whereas `driver.rotate(ScreenOrientation.LANDSCAPE);` works fine - the device is rotated

**Comment by imurchie** [comment]
Ah! Yes, this was forgotten. Adding to the milestone.

**Comment by arompa** [comment]
Thanks!

**Comment by imurchie** [comment]
Available in `appium-xcuitest-driver@2.0.13`
