### ISSUE TITLE
Cleanup process.env.CLOUD

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-xcuitest-driver#1448]
Probably we no longer use `process.env.CLOUD` right now. We may be able to remove relevant code from `test`

**Comment by KazuCocoa** [comment]
REAL_DEVICE flag as well

**Comment by mykola-mokhnach** [comment]
cc @mwakizaka

**Comment by mwakizaka** [comment]
thank you for letting me know. I would try soon. Can we remove `env-base.js`, `env-ios-real.js`, `env-ios-sim.js` and `ios-sim-platforms.js` modules from `test/env` directory? To me it looks like nothing uses the modules.
