### ISSUE TITLE
Doesn't work with C# client?

### ISSUE THREAD

**Issue by Jonahss** [appium/appium-xcuitest-driver#15]
I heard from a user that the C# client doesn't work with this driver. The packets returned for FindElement commands send the ElementID as a string or something unexpected.
https://discuss.appium.io/t/xcuitest-driver/7949

**Comment by StoneTree1** [comment]
When using the C# client I see this error when trying to get an element

> 16 Mar 18:01:18 DEBUG [(null)] - Error caught getting Page name: System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.String'.

In the appium-xcuitest-driver console logging I see 

> info HTTP <-- POST /wd/hub/session 200 39093 ms - 351 
info HTTP --> POST /wd/hub/session/80c0dd26-1fe3-42de-8385-3ad84c51814e/element {"using":"id","value":"page name"}
info MJSONWP Driver proxy active, passing request on via HTTP proxy
info JSONWP Proxy Proxying [POST /wd/hub/session/80c0dd26-1fe3-42de-8385-3ad84c51814e/element] to [POST http://localhost:8100/session/0AF416D3-D376-4048-B2E8-25D51C801D12/element] with body: {"using":"id","value":"page name"}
info JSONWP Proxy Got response with status 200: {"value":{"ELEMENT":4,"type":"UIAElement","label":"UsernamePage"},"sessionId":"0AF416D3-D376-4048-B2E8-25D51C801D12","status":0}
info JSONWP Proxy Replacing sessionId 0AF416D3-D376-4048-B2E8-25D51C801D12 with 80c0dd26-1fe3-42de-8385-3ad84c51814e

I'm guessing the c# driver is expecting "ELEMENT":4 to be returned as "ELEMENT":"4"

I had a look at what Appium 1.4.16 logs to console and it whows the elements value in quotes also

> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"0"},"sessionId":"9e8ac497-79cf-4bca-b499-463d2350cd19"}

**Comment by StoneTree1** [comment]
C# driver works fine with the Appium 1.6.0-beta1
This issue can be closed

**Comment by asnaith** [comment]
I'm also not having any issues so far with the C# Driver (2.0.0.1) in Appium 1.60 release
