### ISSUE TITLE
 xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by 03623170** [appium/appium-xcuitest-driver#154]
Hi, can anyone help?

- Appium v.1.6.0 -beta1
- xcode 8 
- On real iOS device 9.3.5
- .ipa build from Greenhouse CI signed with development profile
- WDA signed with the same profile in WebDriverAgent.xcodeproj

Log:
[XCUITest]
Testing failed:
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[XCUITest] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
TEST FAILED
The following build commands failed:
Check dependencies
(1 failure)
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Error: xcodebuild failed with code 65
at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 27213 ms - 167

Additional Comment:
I also tried to run the tests on a simulator but it only installs the app without being able to open it

**Comment by imurchie** [comment]
See: 

https://github.com/appium/appium-xcuitest-driver/issues/140
https://github.com/appium/appium-xcuitest-driver/issues/106

**Comment by 03623170** [comment]
@imurchie I already tried those steps, but still can't fix the problem. My WDA is signed with the same provisioning profile as the .ipa

**Comment by domuro** [comment]
I'm also getting this issue.  I'm guessing the command to sign the WDA has changed, since I was able to run with no problems several days ago.

Here is the current command appium reports to be using:
`xcodebuild -project /usr/local/avm/versions/1.6.0-beta1/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<UDID> build test`

Here is the command appium reports to use in the readme:
`xcodebuild -project ./WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -sdk iphoneos -destination platform=iOS,id=<UDID> CODE_SIGN_IDENTITY='iPhone Developer' CODE_SIGNING_REQUIRED=YES build test`

I get the issue reported above with the first command I list.  Everything works properly using the latter command.

**Comment by domuro** [comment]
I resolved the issue by fiddling with the WDA Xcode project...

This helped: http://stackoverflow.com/questions/3804191/xcode-codesign-error-code-signing-is-required

Need to specify 'Code Signing Identity' as 'iOS Developer' for WebDriverAgentRunner.

I additionally have checked Automatically manage signing for WebDriverAgentRunner and WebDriverAgentLib.

**Comment by prakashsarav7** [comment]
I am also facing the same!! Any updates on this?

**Comment by anand853** [comment]
even i have same issue. am getting 'xcodebuild exited with code '65' and signal 'null''. pls let me know the solution

**Comment by imurchie** [comment]
What happens when you run the xcodebuild command on its own?

**Comment by timcallanan2** [comment]
I had exactly the same issue and it took me a whole long weekend to get it working, let me describe my steps, hopefully it will help any of you that have the same problems

1. Install Appium 1.6  
2. Download or clone the latest WebDriverAgent for GIT Hub https://github.com/facebook/WebDriverAgent/tree/52a40e332703ebe576f6735ee3cc89be3cb47a25 to your Appium 1.6 location, I have installed to  /Users/<ME>/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
3. Run the Shell script used in GIT hub but use a -d switch to fetch required dependencies 

./Scripts/bootstrap.sh -d

When I ran without the -d switch, I got a lot of errors and I spent for ever trying to fix them. It seems that not all packages are required so using 

./Scripts/bootstrap.sh -d

worked for me

4. Open WebDriverAgent project in Xcode. With IntegrationApp selected as Target, sign the app with the same signature as you are using for you test.ipa file, i.e the IOS app you are testing. Remember you must sign all code/apps you wish to install to a real IOS device , no exceptions 

5. Build WebDriverAgent and install on your IOS real device, it will build, install and launch properly if you have signed it correctly and pulled correct dependencies.  

6. Now You should be all set,  once you can install  WebDriverAgent, you will be abel to launch your test.ipa app and write tests using Appium. I got my first test to pass. 

Hope it works out for you, once you get this setup once it is pretty straightforward but got a bit lost until I found  ./Scripts/bootstrap.sh -d  option,
