### ISSUE TITLE
Great if we have "unicodeKeyboard" and "resetKeyboard" capabilities for iOS device.

### ISSUE THREAD

**Issue by LakshmananKuppan** [appium/appium-xcuitest-driver#1564]
We have "unicodeKeyboard" and "resetKeyboard" capabilities in Android and its makes testers makes life easier.
Kindly develop the similar kind of capabilities for iOS so that we can avoid writing separate line to click return or done button.

It will  be a very useful feature if you guys did this. Kindly consider my voice.

**Comment by jlipps** [comment]
The reason these features exist for Android is that Google has exposed them. For iOS this is not the case. It's not really up to us to develop! But certainly if Apple releases such features we can incorporate them into the driver.
