### ISSUE TITLE
Cannot run tests on Yosemite

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium-xcuitest-driver#16]
After doing the setup asked in README.md I attempted to run the tests on this yosemite. Most of them won't run. Simulator boots up but I don't see the app opening. The webview tests opens up appium but stops immediately. 
![pasted image at 2016_01_25 04_04 pm](https://cloud.githubusercontent.com/assets/149176/12569107/b942e84a-c380-11e5-8a24-77880e034e0f.png)

**Comment by prolificcoder** [comment]
Overall the tests took a long time (15+ mins) and still running, so killed the test run.

**Comment by imurchie** [comment]
Please try the most recent version.
