### ISSUE TITLE
Capturing Performance Data

### ISSUE THREAD

**Issue by trangtran1305** [appium/appium-xcuitest-driver#1625]
i am running it for "Activity Monitor" instead of "Time Profiler", but it didn't work:

File traceZip = new File("/tmp/trace.zip");
  HashMap<String, Object> args = new HashMap<>();
  args.put("timeout", 60000);
  args.put("pid", "current");
  args.put("profileName", "Activity Monitor");
  driver.executeScript("mobile: startPerfRecord", args);
  driver.findElementByAccessibilityId("Search").click();
  Thread.sleep(5000);
  String b64Zip = (String)driver.executeScript("mobile: stopPerfRecord", args);
  byte[] bytesZip = Base64.getMimeDecoder().decode(b64Zip);
  FileOutputStream stream = new FileOutputStream(traceZip);
  stream.write(bytesZip);

**Comment by KazuCocoa** [comment]
Could you explain more and create an issue with filing out the bug template in https://github.com/appium/appium/issues/new ?
