### ISSUE TITLE
XCUITest driver should only require Carthage to be installed if it wasn't already set up

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium-xcuitest-driver#166]
If you already have the WebDriverAgent set up properly (after having executed the bootstrap script once) then Carthage should not be required anymore. This allows to minimize the required dependencies (for example if you want to setup an offline installation).

**Comment by imurchie** [comment]
This is being changed to a warning, rather than an error.

https://github.com/appium/appium-xcuitest-driver/pull/161
