### ISSUE TITLE
Error: The following capabilities were provided, but are not recognized by appium: app

### ISSUE THREAD

**Issue by michaelmendoza42** [appium/appium-xcuitest-driver#17]
I think this is the root cause of the error but I'm seeing a few others in there which may also be relevant:

"The following capabilities were provided, but are not recognized by appium: app" 

"xcodebuild exited with code 70 and signal null"

"Encountered internal error running command: TypeError: Cannot set property 'sessionId' of undefined'

If you need more of the logs let me know.

**Comment by piratmc** [comment]
Same for me 

info WebDriverAgent-driver WebDriverAgent server listening on http://localhost:4723
info HTTP --> POST /wd/hub/session 
info MJSONWP Calling WebDriverAgentDriver.createSession() with args: [{"showIOSLog":true,"app":"/Users/trokd001/Desktop/oneid.app","sendKeyStrategy":"grouped","platformVersion":"8.4","bundleId":"","platformName":"iOS...
WARN BaseDriver The following capabilities were provided, but are not recognized by appium: showIOSLog, app, sendKeyStrategy, bundleId.
info BaseDriver Session created with session id: a2cb33ac-9eea-4715-8735-ed3ca5007e07
info WebDriverAgent-driver Determining device to run tests on
info WebDriverAgent-driver udid not provided, using desired caps to create a new sim
info iOSSim Constructing iOS simulator for Xcode version 7.2
info WebDriverAgent-driver created simulator A998582D-C007-4ED5-98E5-636E5E814F27. Booting it up
dbug WebDriverAgent-driver Checking whether app is actually present
dbug ios-app-utils Getting bundle ID from app
info WebDriverAgent-driver setting up simulator
info iOSSim Constructing iOS simulator for Xcode version 7.2
info iOSSim Constructing iOS simulator for Xcode version 7.2
info WebDriverAgent-driver simulator with udid A998582D-C007-4ED5-98E5-636E5E814F27 not booted. Booting up now
dbug iOSSim Killing all iOS Simulators
info iOSSim Starting simulator with command: open /Applications/Xcode 2.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID A998582D-C007-4ED5-98E5-636E5E814F27
info iOSSim Tailing simulator logs until we encounter the string "profiled: Service starting..."
info iOSSim We will time out after 60000ms
dbug iOSSim Waiting and extra 2000ms for the simulator to really finish booting
dbug iOSSim Done waiting extra time for simulator
info iOSSim Simulator booted in 3204ms
info WebDriverAgent-driver Using default agent
info WebDriverAgent-driver Launching WebDriverAgent on the device
info WebDriverAgent-driver Waiting for WebDriverAgent to start on device
info WebDriverAgent-driver xcodebuild exited with code 70 and signal null
ERR! WebDriverAgent-driver Error: xcodebuild failed with code 70
ERR! WebDriverAgent-driver     at SubProcess.<anonymous> (lib/webdriveragent.js:73:18)
ERR! WebDriverAgent-driver     at emitTwo (events.js:87:13)
ERR! WebDriverAgent-driver     at SubProcess.emit (events.js:172:7)
ERR! WebDriverAgent-driver     at ChildProcess.<anonymous> (lib/teen_process.js:177:14)
ERR! WebDriverAgent-driver     at emitTwo (events.js:87:13)
ERR! WebDriverAgent-driver     at ChildProcess.emit (events.js:172:7)
ERR! WebDriverAgent-driver     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
ERR! WebDriverAgent-driver  [Error: xcodebuild failed with code 70]
info WebDriverAgent-driver Shutting down WebDriverAgent
ERR! MJSONWP Encountered internal error running command: TypeError: Cannot set property 'sessionId' of undefined

**Comment by iquicktest** [comment]
same for me.

info MJSONWP Calling WebDriverAgentDriver.createSession() with args: [{"app":"/Users/jerryzhao/Desktop/HelloWorld.app","locationServicesAuthorized":"false","platformVersion":"9.3","bundleId":"","platformName":"iOS","...
ERR! WebDriverAgent-driver SessionNotCreatedError: A new session could not be created. Details: Cannot create a new session while one is in progress
ERR! WebDriverAgent-driver     at WebDriverAgentDriver.callee$0$0$ (lib/commands/session.js:10:11)
ERR! WebDriverAgent-driver     at tryCatch (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at invoke (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! WebDriverAgent-driver     at enqueueResult (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
ERR! WebDriverAgent-driver     at new Promise (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
ERR! WebDriverAgent-driver     at AsyncIterator.enqueue (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:16)
ERR! WebDriverAgent-driver     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at Object.runtime.async (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
ERR! WebDriverAgent-driver     at WebDriverAgentDriver.callee$0$0 (lib/commands/session.js:8:46)
ERR! WebDriverAgent-driver     at WebDriverAgentDriver.createSession$ (lib/driver.js:17:27)
ERR! WebDriverAgent-driver     at tryCatch (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at invoke (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! WebDriverAgent-driver     at enqueueResult (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
ERR! WebDriverAgent-driver     at new Promise (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
ERR! WebDriverAgent-driver     at AsyncIterator.enqueue (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:16)
ERR! WebDriverAgent-driver     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at Object.runtime.async (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
ERR! WebDriverAgent-driver     at WebDriverAgentDriver.createSession (lib/driver.js:65:29)
ERR! WebDriverAgent-driver     at lib/driver.js:163:24
ERR! WebDriverAgent-driver     at tryCatcher (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
ERR! WebDriverAgent-driver     at Promise._settlePromiseFromHandler (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:507:31)
ERR! WebDriverAgent-driver     at Promise._settlePromiseAt (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:581:18)
ERR! WebDriverAgent-driver     at Promise._settlePromiseAtPostResolution (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:245:10)
ERR! WebDriverAgent-driver     at Async._drainQueue (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
ERR! WebDriverAgent-driver     at Async._drainQueues (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
ERR! WebDriverAgent-driver     at Immediate.Async.drainQueues [as _onImmediate] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
ERR! WebDriverAgent-driver     at processImmediate [as _immediateCallback] (timers.js:367:17)
ERR! WebDriverAgent-driver  { [SessionNotCreatedError: A new session could not be created. Details: Cannot create a new session while one is in progress] jsonwpCode: 33 }
info WebDriverAgent-driver Shutting down WebDriverAgent
ERR! MJSONWP Encountered internal error running command: TypeError: Cannot set property 'sessionId' of undefined
ERR! MJSONWP     at WebDriverAgent.quit$ (lib/webdriveragent.js:148:27)
ERR! MJSONWP     at tryCatch (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! MJSONWP     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at invoke (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! MJSONWP     at enqueueResult (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
ERR! MJSONWP     at new Promise (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
ERR! MJSONWP     at AsyncIterator.enqueue (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:16)
ERR! MJSONWP     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at Object.runtime.async (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
ERR! MJSONWP     at WebDriverAgent.quit (lib/webdriveragent.js:140:14)
ERR! MJSONWP     at WebDriverAgentDriver.deleteSession$ (lib/driver.js:126:22)
ERR! MJSONWP     at tryCatch (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! MJSONWP     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at invoke (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! MJSONWP     at enqueueResult (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
ERR! MJSONWP     at new Promise (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
ERR! MJSONWP     at AsyncIterator.enqueue (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:16)
ERR! MJSONWP     at AsyncIterator.prototype.(anonymous function) [as next] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at Object.runtime.async (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
ERR! MJSONWP     at WebDriverAgentDriver.deleteSession (lib/driver.js:123:16)
ERR! MJSONWP     at WebDriverAgentDriver.createSession$ (lib/driver.js:114:18)
ERR! MJSONWP     at tryCatch (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! MJSONWP     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! MJSONWP     at GeneratorFunctionPrototype.invoke (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! MJSONWP     at run (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
ERR! MJSONWP     at /Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
ERR! MJSONWP     at flush (/Users/jerryzhao/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
ERR! MJSONWP     at process._tickCallback (node.js:355:11)
info HTTP <-- POST /wd/hub/session 500 14 ms - 181

**Comment by midopa** [comment]
Seeing this behavior also.

Appium Java client 3.4.1
Node 6.1.0
XCUITest driver @ commit e39444d

https://gist.github.com/midopa/135edda5176b543db7adc567692690dc

**Comment by imurchie** [comment]
Desired capability validation has been implemented, so this should no longer be an issue. There may be some things that have slipped through the cracks, but the basics are there.

```
info XCUITest XCUITestDriver server listening on http://localhost:4994
info HTTP --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/isaac/code/appium-xcuitest-driver/node_modules/ios-uicatalog/build/Release-iphonesimulator/UICatalog-iphonesimulator.app","platformName":"iOS","platformVersion":"10.0","deviceName":"iPhone 6","automationName":"XCUITest"}}
info MJSONWP Calling XCUITestDriver.createSession() with args: [{"app":"/Users/isaac/code/...
info BaseDriver Session created with session id: f284c97c-6435-4cf7-ada6-605f71a93b59
info iOSSim Constructing iOS simulator for Xcode version 8.0 with udid '8C19F672-8309-4934-8E07-C3261565C31D'
info XCUITest Determining device to run tests on: udid: '8C19F672-8309-4934-8E07-C3261565C31D', real device: false
dbug XCUITest Checking whether app is actually present
dbug ios-app-utils Getting bundle ID from app
dbug iOSLog Starting iOS 10.0 simulator log capture
```

**Comment by mushtaque87** [comment]
Guys make sure you are signing the project for WebDriverAgent.xcodeproj  in /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ .   Dont just download the project to desktop or download folder and try to sign the project . 


After installing appium-xcuitest-driver in your system . go to this location /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ and sign .. this is where appium terminal command pics the WebDriverAgentRunner and build it .
