### ISSUE TITLE
reset Sim doesn't seem to work as expected

### ISSUE THREAD

**Issue by huminzhi** [appium/appium-xcuitest-driver#177]
I didn't specify the UUID, so supposedly "reset" should totally reset the simulator (uninstall the app).. However, from what I see, it just shutdown then re-open simulator, it doesn't really 'reset'

**Comment by imurchie** [comment]
Can you provide the appium server logs so we can see what is the particular configuration and what the system is doing? Otherwise there is not much to go on here.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7426](https://github.com/appium/appium/issues/7426) via [**ZenHub**](https://www.zenhub.com/)
