### ISSUE TITLE
docs does not have proper alias

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-xcuitest-driver#1780]
`--update-aliases "$doc_v" latest` in https://github.com/appium/appium-xcuitest-driver/commit/20a0d01f928ed41bb678a913345dfb8fe45a06ab made no update for the alias to the latest version.
I'll take a look later.
Expected behavior is https://appium.github.io/appium-xcuitest-driver/latest will redirect to the latest one.
https://github.com/appium/appium-xcuitest-driver/blob/docs-site/versions.json (manually updated a bit, but maybe not worked well?)

**Comment by jlipps** [comment]
hmm, i think `--update-aliases` is part of the appium docs build, or supposed to be

**Comment by KazuCocoa** [comment]
Ok, maybe the versioning is a bit wrong.
Expected https://github.com/appium/appium/blob/ed20e007548e10f89a5212b2868ed7ec47f51c2a/packages/docutils/lib/builder/deploy.ts#L59 is MAJOR.MINOR, but currently https://github.com/appium/appium-xcuitest-driver/tree/docs-site and the `versions.json` has the patch version info as well. It configures the 'latest' alias wrongly.

**Comment by KazuCocoa** [comment]
Created a pr
