### ISSUE TITLE
About the Validity Period of Real Machine Testing

### ISSUE THREAD

**Issue by 15313388469** [appium/appium-xcuitest-driver#1860]
What is the validity period of the testing project if we test it on a real machine? Because I found out that I installed it on the device two weeks ago and now it says it's expired

**Comment by KazuCocoa** [comment]
Do you mean Apple's provisioning profiles? It depends on your provisioning profile configuration. If it was a free account, perhaps it is usually a week or so

**Comment by 15313388469** [comment]
> 

Yes, but my account is not free, it's a corporate account. It seems that the validity period is only one or two weeks, which is a bit strange.

**Comment by KazuCocoa** [comment]
Then, asking Apple support might be proper since we don't know about their internal. Appium/WDA follows Xcode/xcodebuild as same as regular apps. Perhaps if your device was in good network condition environment, iOS verifies it via the internet
