### ISSUE TITLE
Build Error while building for iOS 10.0 : 'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from <stdatomic.h> instead

### ISSUE THREAD

**Issue by vikaspune** [appium/appium-xcuitest-driver#188]
While setting up automation with Appium 1.6 beta with iOS 9.3.X and iOS 10.0
For iPhone with iOS 9.3.X, Webdriver agent got installed on mobile device and working as expected when i start a new appium session with XCUITEST automation name. I also used `xcodebuild` command with test target as mentioned in documents and this also worked.

But for iPhone with iOS 10.0, I changed IOS Development target to iOS 10.0 for project and all targets but when I build project  I am getting below error. 

```
Testing failed:
	'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from <stdatomic.h> instead
** TEST FAILED **
```

I tried building from XCode UI and still was getting same error, please check snap below.

![screen shot 2016-09-27 at 3 21 24 pm](https://cloud.githubusercontent.com/assets/10324878/18871969/951d79fa-84d5-11e6-8a55-ed861d783fd7.png)

I am not sure I am doing something wrong.

I am using below environment
Xcode: 8
iOS SDK 10
iPhone 5c (iOS 9.3.5)
iPhone 6 (iOS 10)
With Apple Developer profile
Not tried on simulator yet.

**Comment by imurchie** [comment]
Is this Xcode 8 GA?

I would try re-loading `appium-xcuitest-driver` to get a new copy of the WebDriverAgent code. You can try locally by running `npm install appium-xcuitest-driver` and then opening `node_modules/appium-xcuitest-driver/WebDriverAgent` in Xcode and building.

**Comment by vikaspune** [comment]
Thanks for quick response . I am using xcode 8, not GA. As you mention I
will try reloading appium-xcuitest-driver and will update here.

Thanks you for reply.
Vikas

**Comment by imurchie** [comment]
Sorry, by GA I mean the full Xcode 8 release. Not one of the (many many) betas?

**Comment by vikaspune** [comment]
I apologies for misunderstanding. Yes I am using full version not any beta.

I will give a try with reinstalling tomorrow my morning as I don't have
access to my machine.

I also have xcode 7.3 installef but in different folder and I selected
xcode8 as default using xcode-select, you think this might be causing this
issue?


Vikas

**Comment by imurchie** [comment]
The upstream project had this issue, which was the same:

https://github.com/facebook/WebDriverAgent/issues/194#issuecomment-230907439

**Comment by vikaspune** [comment]
Hi @imurchie , 
I uninstalled appium-xcuitest-driver using `npm uninstall` and re-installed with `npm install -g' but did not help. 

neither rebooting OS X helped.

**Comment by imurchie** [comment]
Did you uninstall appium? I don't think doing the xcuitest driver alone will do anything.

I would also delete any old version of WebDriverAgentRunner off the device.

**Comment by vikaspune** [comment]
I haven't uninstalled Appium considering appium-xcuitest-driver is separate node module.

I wanted to get WebDriverAgentRunner installed on ios10 device so only using xcodebuild command and webdriveragent program.

If you still think uninstalling appium1.6beta will help I can try it.

**Comment by imurchie** [comment]
`appium-xcuitest-driver` is used by Appium. Just re-installing the former doesn't mean that the latter is using the new version.

When you use the xcodebuild command does the error still happen?

**Comment by vikaspune** [comment]
Yes , For xcodebuild command same error. I am reinstalling appium now and will update here. Thanks

**Comment by imurchie** [comment]
If the base system doesn't work then Appium will not either. I guess we have to wait until that issue is resolved there.

**Comment by vikaspune** [comment]
Yes makes sense. Can anybody  do me a favour, as I have seen some posts saying webdriver agent works with ios10, somehow I feel I am doing something wrong while setting up all the things, can anybody please try building and installing webdriver agent runner for ios10 device, just  to confirm its not configuration issue and this Shuld be a blocker.

**Comment by vikaspune** [comment]
Hi @imurchie ,
Today I got update from WebDriverAgent project that https://github.com/facebook/WebDriverAgent/issues/302#issuecomment-250433267 is now fixed. 

Is it possible to get the latest WebDriverAgent code into our appium-xcuitest-driver project?

**Comment by imurchie** [comment]
Yes. I'm just running tests to make sure everything continues to work. They sometimes change things that force us to modify our integration.

**Comment by vikaspune** [comment]
Agree, thank you very much @imurchie

**Comment by imurchie** [comment]
Fixed in the upstream project, available in `appium-xcuitest-driver@2.0.20`.

**Comment by vikaspune** [comment]
Thank you @imurchie , I will test this today and update comment here.

**Comment by vikaspune** [comment]
Confirming this is fixed. though I am getting a new error which is not relevant to this this bug. So we can close this issue now.
