### ISSUE TITLE
How to avoid "Trust ... Apps on This iPhone " in setting>VPN&Device Management when I install wda

### ISSUE THREAD

**Issue by pppppino** [appium/appium-xcuitest-driver#1970]
My wda is built by my free apple account, so it will expired in 7 days.

After installed wda in my iPhone, I must goto Phone Setting/VPN&Device Management to trust wda, Do we have any method to trust this wda forever, so I don't need to trust it at every turn.

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/issues/762
