### ISSUE TITLE
ProcessArguments JSON conversion issue

### ISSUE THREAD

**Issue by ol-le** [appium/appium-xcuitest-driver#199]
I am adding processArguments capability in a new JSON format: 
(Java example)
```java
JSONObject processArguments = new JSONObject();
processArguments.put("arguments", "UI_AUTOMATION");
capabilities.setCapability("processArguments", processArguments);
```

this is how the request looks like
```
info HTTP --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/olgav/Downloads/test.app","platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","processArguments":{"hCode":18179709,"class":"org.json.JSONObject"},"deviceName":"iPhone 6"}}
```

if I pass it as a string value: 
```
JSONObject processArguments = new JSONObject();
processArguments.put("arguments", "UI_AUTOMATION");
capabilities.setCapability("processArguments", processArguments.toString());
```

The request:
```
info HTTP --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/olgav/Downloads/test.app","platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","processArguments":"{\"arguments\":\"UI_AUTOMATION\"}","deviceName":"iPhone 6"}}
```

What I am expecting is:
```
info HTTP --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/olgav/Downloads/test.app","platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","processArguments":{"arguments":"UI_AUTOMATION"},"deviceName":"iPhone 6"}}
```

It seems that BeanToJsonConverter tries to convert this value as a sequence of chars and i got escaped characters in the requests and as a result the argument is not passed correctly.
 Am I wrong? Any ideas?

**Comment by imurchie** [comment]
This seems like an issue with the Java client.

**Comment by imurchie** [comment]
What is the error that happens here when the string is escaped? Does it happen if you use `args` instead of `arguments` (see https://github.com/appium/appium-xcuitest-driver#usage)?

It all works fine to me.

**Comment by ol-le** [comment]
Thanks for a quick reponse. I tried using 'args' but I got the error message that the JSON object format is wrong.
When the string is escaped it is ignored and the app starts without sent arguments.

**Comment by imurchie** [comment]
Can you provide the server logs? It is not possible to tell what is happening through vague descriptions.

**Comment by ol-le** [comment]
The problem is on my side. 
Even if I have only one argument I have to create an Array and put this value into it.
So the correct way to use this capability is: 

 ArrayList<String> args = new ArrayList<>();
 args.add("UI_AUTOMATION");

 JSONObject processArguments = new JSONObject();
 processArguments.put("args", args);
 capabilities.setCapability("processArguments", processArguments.toString());

Thanks for your help. The issue can be closed
