### ISSUE TITLE
get_attribute on "hint" gives WebDriverException

### ISSUE THREAD

**Issue by lallish** [appium/appium-xcuitest-driver#216]
**I run appiym-python-client 0.22 with appium 1.6.0-rc-2 and do iOS 10 automation testing, building my app in Xcode 8. With the Xcode update I had to scrap UIAutomation and switch to XCUITests. My app saves data in the "hint" attribute for different elements in the app, so that I can fetch this data in the appium tests. But there is a problem when I try to call get_attribute("hint") on my element, I get this response in the appium log, where "elem" is an element I've found through driver.find_element_by_name**: 

<<< elem.get_attribute("hint")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/larsrn/.virtualenvs/env1/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 111, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/Users/larsrn/.virtualenvs/env1/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Users/larsrn/.virtualenvs/env1/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/larsrn/.virtualenvs/env1/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: [<XCElementSnapshot 0x17436f240> valueForUndefinedKey:]: this class is not key value coding-compliant for the key wdHint.

(
	0   CoreFoundation                      0x00000001825041d8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180f3c55c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182503e88 <redacted> + 0
	3   Foundation                          0x0000000182fa5500 <redacted> + 248
	4   Foundation                          0x0000000182eec3a8 <redacted> + 264
	5   WebDriverAgentLib                   0x0000000103fa2a94 -[XCElementSnapshot(WebDriverAttributes) fb_valueForWDAttributeName:] + 108
	6   WebDriverAgentLib                   0x0000000103fb1e80 +[FBElementCommands handleGetAttribute:] + 408
	7   WebDriverAgentLib                   0x0000000103f9e780 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	8   WebDriverAgentLib                   0x0000000103f973a4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	9   RoutingHTTPServer                   0x00000001040763cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	10  RoutingHTTPServer                   0x0000000104076b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	11  libdispatch.dylib                   0x000000018138d1c0 <redacted> + 16
	12  libdispatch.dylib                   0x000000018139e0c4 <redacted> + 320
	13  libdispatch.dylib                   0x000000018138d1c0 <redacted> + 16
	14  libdispatch.dylib                   0x0000000181391d6c _dispatch_main_queue_callback_4CF + 1000
	15  CoreFoundation                      0x00000001824b1f2c <redacted> + 12
	16  CoreFoundation                      0x00000001824afb18 <redacted> + 1660
	17  CoreFoundation                      0x00000001823de048 CFRunLoopRunSpecific + 444
	18  Foundation                          0x0000000182eecb1c <redacted> + 304
	19  Foundation                          0x0000000182f412a0 <redacted> + 88
	20  WebDriverAgentLib                   0x0000000103f96424 -[FBWebServer startServing] + 320
	21  WebDriverAgentRunner                0x00000001003f3ed0 -[UITestingUITests testRunner] + 120
	22  CoreFoundation                      0x000000018250a160 <redacted> + 144
	23  CoreFoundation                      0x00000001823fdc3c <redacted> + 284
	24  XCTest                              0x000000010022e34c __24-[XCTestCase invokeTest]_block_invoke_2 + 388
	25  XCTest                              0x0000000100262e9c -[XCTestContext performInScope:] + 208
	26  XCTest                              0x000000010022e1b0 -[XCTestCase invokeTest] + 268
	27  XCTest                              0x000000010022e884 -[XCTestCase performTest:] + 460
	28  XCTest                              0x000000010022bd00 -[XCTestSuite performTest:] + 428
	29  XCTest                              0x000000010022bd00 -[XCTestSuite performTest:] + 428
	30  XCTest                              0x000000010022bd00 -[XCTestSuite performTest:] + 428
	31  XCTest                              0x0000000100217c74 __25-[XCTestDriver _runSuite]_block_invoke + 56
	32  XCTest                              0x0000000100238504 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 528
	33  XCTest                              0x0000000100217b0c -[XCTestDriver _runSuite] + 460
	34  XCTest                              0x0000000100218890 -[XCTestDriver _checkForTestManager] + 296
	35  XCTest                              0x0000000100264368 _XCTestMain + 628
	36  CoreFoundation                      0x00000001824b2160 <redacted> + 20
	37  CoreFoundation                      0x00000001824b195c <redacted> + 288
	38  CoreFoundation                      0x00000001824af7b0 <redacted> + 788
	39  CoreFoundation                      0x00000001823de048 CFRunLoopRunSpecific + 444
	40  GraphicsServices                    0x0000000183e61198 GSEventRunModal + 180
	41  UIKit                               0x00000001883b8628 <redacted> + 684
	42  UIKit                               0x00000001883b3360 UIApplicationMain + 208
	43  XCTRunner                           0x000000010008c3d4 XCTRunner + 33748
	44  libdyld.dylib                       0x00000001813c05b8 <redacted> + 4
)

<<<

**Here are my capabilities:**
        self.desired_caps['realDeviceLogger'] = 'idevicesyslog'
        self.desired_caps['platformName'] = 'iOS'
        self.desired_caps['platformVersion'] = '10.0'
        self.desired_caps['automationName'] = 'XCUITest'
        self.desired_caps['deviceName'] = 'iPhone Simulator'
        self.desired_caps['udid'] = 'auto'
        self.desired_caps['app'] = self.app_file
        self.desired_caps['newCommandTimeout'] = '6000'

**get_attribute on other attribute works, such as get_attribute("label"), any ideas why the hint attribute causes this exception?**

**Comment by imurchie** [comment]
I don't think that `hint` is an attribute that can be retrieved.

**Comment by benzhou1** [comment]
How do we know all the available attributes that we can retrieve? Is there a way to get this list?

**Comment by imurchie** [comment]
I've queried the upstream project. I will post here when hear anything.

**Comment by lallish** [comment]
> I don't think that hint is an attribute that can be retrieved.
It was possible when I built with Xcode 7 and used UIAutomation. But things might have changed. At the moment I managed to store my app information in "label" so things have worked out. But still curious why hint doesn't work!

**Comment by imurchie** [comment]
This is the list of attributes: https://github.com/facebook/WebDriverAgent/blob/6813e2549b684379e1b6a6ee96deb2b42f4e1a85/WebDriverAgentLib/Routing/FBElement.h

**Comment by lallish** [comment]
Thanks :)
