### ISSUE TITLE
Pull latest WebDriverAgent

### ISSUE THREAD

**Issue by kaleposhobios** [appium/appium-xcuitest-driver#22]
There have been a few months worth of changes in WebDriverAgent. Can these be pulled in?

**Comment by StoneTree1** [comment]
+1 to this. The latest version(1.0.1) of appium-xcuitest-driver on npm seems like it may have a broken version for WebDriverAgent bundled into it.

**Comment by Jonahss** [comment]
@imurchie can you handle this? I can walk you through the process.

**Comment by imurchie** [comment]
Sure.
