### ISSUE TITLE
xcodeConfigFile path cannot contain spaces

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium-xcuitest-driver#224]
When using the xcodeConfigFile capability, if the path to the file contains spaces, the run-xcodebuild.sh script will split it into separate arguments, causing xcodebuild to fail with error code 127.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7430](https://github.com/appium/appium/issues/7430) via [**ZenHub**](https://www.zenhub.com/)
