### ISSUE TITLE
[XCUITest] Unable to start WebDriverAgent: Error: spawn EACCES

### ISSUE THREAD

**Issue by seanchandler** [appium/appium-xcuitest-driver#227]
iOS 10.0.2
xcode 8
appium 1.6.0-beta3
appium-xcuitest-driver 2.0.26

Seeing same issue in [Issue #191 ](https://github.com/appium/appium-xcuitest-driver/issues/191) on a real device, simulator is ok.

```
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] Unable to start WebDriverAgent: Error: spawn EACCES
[XCUITest] Unable to start WebDriverAgent: Error: spawn EACCES
[debug] [XCUITest] Reset not set, continuing
[debug] [iOSLog] Stopping iOS log capture
```

This happens when I use deviceconsole, without it I see the hang from [Issue #6895](https://github.com/appium/appium/issues/6895)

On the device itself, I see wda installed on the phone and start/background within a few seconds (up to 10 sometimes) after the error.

I'm able to run the xcodebuild command outside of appium and arrive at Listening on USB

Looking for insights on how to further troubleshoot this, if there's any additional info you'd like me to submit let me know - thanks!

**Comment by puneetkaur11** [comment]
I am having similar issue, I am able to run xcodebuild command too and get the message Listening on USB at the end.

**Comment by dumplincat** [comment]
iOS 9.0
iOS 9.3.4
xcode 7.3.1
appium 1.6.0-beta3
appium 1.6.0

same issue.

**Comment by imurchie** [comment]
Can you run `iproxy`? If you run `iproxy 8100 8100`?

**Comment by imurchie** [comment]
Second thought: Do you have `idevicesyslog` installed?

**Comment by imurchie** [comment]
Sorry, just saw that you were using `deviceconsole`. 

Figured it out!

I think you are pointing `realDeviceLogger` to the directory, rather than the executable. For instance, I have `deviceConsole` installed in

```
/Users/isaac/.nvm/versions/node/v4.4.7/lib/node_modules/deviceconsole
```

So the actual executable, which is what `realDeviceLogger` should be pointing to, is

```
/Users/isaac/.nvm/versions/node/v4.4.7/lib/node_modules/deviceconsole/deviceconsole
```

**Comment by seanchandler** [comment]
@imurchie thanks, setting path to the binary worked.

**Comment by imurchie** [comment]
Excellent. I've got some work in progress to make it more clear, and automatically fix it. Not that that helps you, but this issue has cleaned up some stuff. So thanks!

**Comment by michalakm** [comment]
@seanchandler Thanks for the issue. I made the same mistake.
