### ISSUE TITLE
Need to coordinate next WDA update

### ISSUE THREAD

**Issue by yaphatak** [appium/appium-xcuitest-driver#228]
[PR](https://github.com/facebook/WebDriverAgent/pull/310) to `scrollIntoView` got merged. So with next `WDA` update we should also get rid of [this](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L14)

**Comment by imurchie** [comment]
Sorry, I missed this. 

WDA has been updated since then. Do you want to remove the local logic?

**Comment by yaphatak** [comment]
I guess this should do https://github.com/appium/appium-xcuitest-driver/pull/233
