### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by ewscripps-jb** [appium/appium-xcuitest-driver#2288]
% appium driver update xcuitest
✔ Checking if driver 'xcuitest' is updatable
✔ Checking if driver 'xcuitest' needs an update
⠋ Updating driver 'xcuitest' from 5.11.0 to 5.12.2⠋ Installing 'xcuitest' using ✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver@5.12.2'
✖ Updating driver 'xcuitest' from 5.11.0 to 5.12.2
ℹ Update report:
✖   - 'xcuitest' failed to update: Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --prefer-offline --omit=peer --save-exact --global-style --no-package-lock appium-xcuitest-driver@5.12.2 --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "ETARGET",
    "summary": "No matching version found for appium-xcuitest-driver@5.12.2.",
    "detail": "In most cases you or one of your dependencies are requesting\na package version that doesn't exist."
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm ERR! code ETARGET
npm ERR! notarget No matching version found for appium-xcuitest-driver@5.12.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/164485/.npm/_logs/2024-01-03T11_26_10_766Z-debug-0.log

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/pull/19571 will improve this.
Current workaround is `npm cache clean --force` on your local to clear the local cache
