### ISSUE TITLE
Help with extending desired capabilities

### ISSUE THREAD

**Issue by matyashlavacek** [appium/appium-xcuitest-driver#23]
Hey guys, 

I'm having trouble finding out how to add desired capabilities to this driver and I would really appreciate if someone could point me in the right direction. (Where to look, so I can try to implement it)

I want to add 'processArguments' capability, which already works standard appium driver, to be able to pass arguments to the app I'm launching.

Here is the log:
`info MJSONWP Calling WebDriverAgentDriver.createSession() with args: [{"app":"path-to.app","platformVersion":"9.2","platformName":"iOS","processArguments":"-ARG FUBAR"...`

`WARN BaseDriver The following capabilities were provided, but are not recognized by appium: app, processArguments.`

Which seems a bit strange, as it actually passes the "app" argument as I can successfully launch my application:

`info JSONWP Proxy Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"app":"path-to.app","bundleId":"com.fu.bar"}}`

And I'd love to pass the "processArguments"  here too.

Any help would be really appreciated.

Thanks!

**Comment by Jonahss** [comment]
Cool! This is how it works:

The [BaseDriver](https://github.com/appium/appium-base-driver) class has default capabilities, and each driver that extends it can add their own capabilities.

See this code in the AndroidDriver? https://github.com/appium/appium-android-driver/blob/master/lib/driver.js#L39

That's where we add the custom desired caps for the android driver on top of the default desired caps. It looks like it's setting it equal there, but that variable actually has a setter that adds the defaults.

Here's the line where the custom caps are loaded: https://github.com/appium/appium-android-driver/blob/master/lib/driver.js#L3

And here's where they are defined: https://github.com/appium/appium-android-driver/blob/master/lib/desired-caps.js

Right now, it looks like the XcuitestDriver is only using the default desired caps. So you'll have to add these on, the same way they work in AndroidDriver. But choose just your additional desired caps of course.

Is this clear? Any other questions? I'm glad to help :)

**Comment by matyashlavacek** [comment]
Thanks a lot for the info! :) _...and sorry for the late reply, I had a rough weekend :/_
It's pretty clear to me know and after implementing it, it works.

I have some other questions though:
I've looked inside the WebDriverAgent and found how it gets app's launch arguments/environment from the POST request to /session:
https://github.com/appium/WebDriverAgent/blob/bba1a925e7135058a30f645f54fcecd67e1ab9bf/XCTWebDriverAgentLib/Commands/FBSessionCommands.m#L35
`app.launchArguments = requirements[@"arguments"] ?: @[];`
`app.launchEnvironment = requirements[@"environment"] ?: @{};`

There is the appium's iOS only 'processArguments' capability for this, and I'm using this capability to send launch arguments to the WDAgent, but haven't found any specification for it: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L227
Therefore I've implemented only the arguments part and skipped the launch environment part for now. 

Could you please take a look if it's ok to implement it like this, if I should do it in a better way or if there are some things I'm doing/approaching wrong?
https://github.com/appium/appium-xcuitest-driver/pull/24/files

_Please note that this is my first attempt to contribute to public repository, so I'm not sure if creating a pull request at this stage was the correct decision_

**Comment by Jonahss** [comment]
Awesome, glad the info was useful.
Hope you have a less rough week.

You can go ahead and submit your changes as a Pull Request. Then I can add comments to the code itself and we can work through it until it's ready to be merged :)


Glad you chose to enter the Open Source world :)

**Comment by matyashlavacek** [comment]
Yeah, thanks for the warm welcome :)

I've created the PR: https://github.com/appium/appium-xcuitest-driver/pull/26

I've also noticed the unit test are failing for my PR, so I'll take a look on that in the meanwhile.
