### ISSUE TITLE
Request failed with status 404 due to no such alert when no dialog is shown

### ISSUE THREAD

**Issue by rolandmoldovan** [appium/appium-xcuitest-driver#2349]
Is there a way to prevent "_ERROR webdriver: Request failed with status 404 due to no such alert_" when a native iOS system dialog isn't displayed but trying to check and accept it if its there?
It seems like even when using a try-catch block, Appium still throws the error. Since driver.isAlertOpen() is specific to Chromium protocols, I've been trying other approaches such as getAlertText but this throws when dialog is not displayed even in a try catch block. Thank you!

```
      try {
        const alertText = await driver.getAlertText();
        if (alertText) {
          await driver.acceptAlert();
        }
      } catch (error) {}
```

**Comment by sbolka** [comment]
Can't detect native iOS Alert pop-up asking for notification permission with latest v7.4.0 driver version.
At the same time everything works fine with xcuitest@5.8.2 (Appium 2.4.1)

**Comment by bronik** [comment]
I think my issue related to this problem. If I'm wrong - please tell me and I'll create separate issue

appium 2.5.1
xcuitest 7.8.2
can't locate and, as a result, perform click on native dialog buttons (such as permissions). trying to find elements by accessibility id 
accessibility inspector (2023.11.1) do found those elements by the same locator and can perform tap on them

I've tried xcuitest@5.6.0 - everything work as expected (can find native dialog buttons and click on them by the same locators)

**Comment by eglitise** [comment]
[Please refer to the XCUITest documentation on handling native dialogs](https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard).

**Comment by PetroAndrushchak** [comment]
same issue here, Appium Inspector can locate IOS alert

**Comment by RavNowak** [comment]
The problem is that driver.acceptAlert() displays an error messages on iOS even we catch the error

**Comment by jlipps** [comment]
@RavNowak please open up a new issue and include your appium and client logs if you want us to look at this. this particular issue seems old and does not have appropriate logs.
