### ISSUE TITLE
After upgrading to latest version of xcuitest driver @7.15.1

### ISSUE THREAD

**Issue by CarsonFobo** [appium/appium-xcuitest-driver#2390]
i get previous error when i start my testing

Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Real device architecture is not supported by the my.com.salutica.fobotpms application. Make sure the correct deployment target has been selected for its compilation in Xcode.

**Comment by KazuCocoa** [comment]
Could you create a bug report ticket from the template with proper logs in https://github.com/appium/appium/issues/new/choose ?

The message usually means the given package might not have proper architecture binary for real devices
https://github.com/appium/appium-xcuitest-driver/blob/32227b4e19562cfc913d77caf69137f903b78b6f/lib/app-utils.js#L47-L54

**Comment by CarsonFobo** [comment]
But i didn't encounter any issue when i'm using xcuitest driver @5.16.1 with same ipa. Please advice

{
  "appium:deviceName": "iPhone 12",
  "platformName": "ios",
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "17.1.2",
  "appium:udid": "00008101-001C6C993061401E",
  "appium:xcodeOrgId": "UCU4RKBR27",
  "appium:xcodesigningId": "iPhone Developer",
  "appium:bundleId": "my.com.salutica.fobotpms",
  "appium:app": "//Users//carson//Desktop//FOBO APP IPA File//FOBO TPMS v1.9.ipa"
}

**Comment by KazuCocoa** [comment]
Yes, so could you create a bug report ticket from the template with proper logs in https://github.com/appium/appium/issues/new/choose ? Logs could tell something more, which might not occur our testing

**Comment by KazuCocoa** [comment]
btw, appium checks if the given app's `Info.plist` has `CFBundleSupportedPlatforms` and the body as verification you addressed. Usually Xcode automatically adds the value, so please share the full appium log when you create an issue from the attached url above.
