### ISSUE TITLE
WDA configuration issue

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium-xcuitest-driver#240]
Hi 
I am trying to install the appium v1.6 , I have followed the following steps
$ npm install -g appium 
$ /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
$ brew install carthage --HEAD
$ npm install web pack -g
$ mkdir -p Resources/WebDriverAgent.bundle
$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=UDID’ test

And it is getting struck at a particular point , i have linked the [gist](https://gist.github.com/pavanbachu0604/fb2a9c4930c888ff4b8d7ea684814a2b)

**Comment by imurchie** [comment]
I don't understand why you are doing most of this. All you need to do is install Appium (`npm install -g appium`) and have Carthage installed (`brew install Carthage`). webpack is unnecessary as is making the bundle directory. And the xcodebuild command will run the WebDriverAgent tests, which is probably not something you want to do.

**Comment by pavanbachu0604** [comment]
Dont we need to set the provisioning profiles ? I am kinda confused , can you please document the steps for installing appium for running on a real devices(both Grid and individual devices).

**Comment by imurchie** [comment]
The easiest and best way (best because you don't need to do it over and over again, every time the system changes) is to use an xcode config file. See https://github.com/appium/appium-xcuitest-driver#configuration
