### ISSUE TITLE
Unable to find native elements after switching from webview

### ISSUE THREAD

**Issue by midopa** [appium/appium-xcuitest-driver#241]
1. Setup a local server with a self-signed certificate
1. Setup and launch Appium for a browser session
1. Navigate to the local server
1. A certificate alert will appear
1. Switch to the NATIVE_APP context
1. Try to find the alert dialogue using XPath: `//XCUIElementTypeAlert`
1. That doesn't work, even though the element exists when I get the page source: `driver.getPageSource()`:
```
<XCUIElementTypeAlert name="Cannot Verify Server Identity" label="Cannot Verify Server Identity" ...
```

Logs: https://gist.github.com/midopa/fc9cc793431c187243fa91ad1f2bdfe8

Appium 1.6.0
Node 6.7.0
Java client 4.1.2 (5.0 isn't out yet which will have support for predicate strings)
OSX El Capitan
XCode 8
iOS 10 simulator (iPad Air)

Capabilities:
```
{
  networkConnectionEnabled=false,
  noReset=false,
  databaseEnabled=false,
  deviceName=iPad Air,
  platform=MAC,
  showIOSLog=true,
  sendKeyStrategy=grouped,
  newCommandTimeout=10000,
  platformVersion=10.0,
  safariAllowPopups=true,
  webStorageEnabled=false,
  locationContextEnabled=false,
  browserName=safari,
  takesScreenshot=true,
  javascriptEnabled=true,
  platformName=iOS
}
```

## Extra 1

1. However, several elements are returned if I use a generic XPath search: `//*`
1. If I try to call `getTagName()` on the first element from that list, I get a WebDriverException. 

Log: https://gist.github.com/midopa/a2a6be8da402711960b3518ae4e45233

## Extra 2

1. If I do the same query above and do `getCenter()` instead, I get a NullPointerException.

Log: https://gist.github.com/midopa/523e341ced71063a18ded0f6e3d19bbd

**Comment by imurchie** [comment]
Strange. I can get the alert and accept it. `https://localhost:8000` is a local server with a self-signed certificate.

```
    await driver.get('https://localhost:8000');
    await driver.context('NATIVE_APP');
    let el = await driver.elementByClassName('XCUIElementTypeAlert');
    let btn = await el.elementByClassName('XCUIElementTypeButton');
    await btn.click();
```

**Comment by midopa** [comment]
Is that the same as using XPath?

**Comment by imurchie** [comment]
The same? No, it is calling different things underneath. Xpath is awful, this works fine.

**Comment by midopa** [comment]
Can you repro the problem using XPath?

XPath is awful to look at, but sometimes (usually in native contexts) it's the most flexible locator strategy (where writing things like sibling-of-element in predicate syntax is very verbose or not possible).

**Comment by imurchie** [comment]
I have opened a PR to help with this.

**Comment by imurchie** [comment]
The latest published version of the xcuitest driver should better handle this. It seems to work for me. Can you try it out?

**Comment by midopa** [comment]
Hm, it still doesn't work for me.

I modified the package.json in my local copy of Appium (checked out at the `v1.6.0` tag), re-built, and re-ran.

Then I started the driver, navigated to the page, and:
```
appium.context("NATIVE_APP"); // since I'm trying to find the alert window
appium.findElementByClassName("XCUIElementTypeAlert"); // not found exception
appium.findElementByXPath("//XCUIElementTypeAlert"); // not found exception
appium.findElementsByXPath("//*"); // returns something, but I don't know what they are because of the other issues I mentioned in the bug
appium.getPageSource(); // returns source and alert is clearly in there
```

The page source I get back from Appium: https://gist.github.com/midopa/8aea74512c4aa5dd848929462b3a5f23

**Comment by imurchie** [comment]
Can you post the logs?

**Comment by midopa** [comment]
https://gist.github.com/midopa/14db418d86597939d80bbe5f79a5a0f2

I've added new lines to help separate out the calls.
This is the code I ran:
```
driver.get('https://ui-derp.com')
driver.switch_to.context('NATIVE_APP')
driver.find_element_by_xpath('//XCUIElementTypeAlert')
```

**Comment by midopa** [comment]
Wait a minute, according to the logs, 2.0.26 was used??? Hmm

**Comment by imurchie** [comment]
You will need to do an `npm install`. Maybe `rm -rf node_modules && npm install`.

**Comment by midopa** [comment]
The problem was the npm-shrinkwrap.json file. I removed it and ran npm install again and the correct driver version was picked up. I'll rerun my mini test.

**Comment by imurchie** [comment]
Ah. Makes sense. I would just run off of master instead of the 1.6 branch. All development is done there, and then cherry-picked into the release branch.

**Comment by midopa** [comment]
Works! Thank you!

Bonus: The "extras" also work now too!

**Comment by imurchie** [comment]
Awesome!
