### ISSUE TITLE
appium wda real device test error

### ISSUE THREAD

**Issue by tanhaipeng** [appium/appium-xcuitest-driver#243]
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=***' test

**error:**
![image](https://cloud.githubusercontent.com/assets/3655462/19430401/a82d5770-9486-11e6-867b-a214db745396.png)

**Comment by imurchie** [comment]
Are you signing everything properly?

**Comment by pavanbachu0604** [comment]
@tanhaipeng : I feel its a code signing issue
