### ISSUE TITLE
 iOS 8 devices not working on Appium 1.6 WDA

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium-xcuitest-driver#248]
## The problem

Unable to sign the WDA on iOS 8 devices, i'm getting the following error message
"UI Testing is not supported on “iPad” because it is running iOS 8.1 and UI Testing requires iOS 9.0 or later."
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.6
- Last Appium version that did not exhibit the issue (if applicable): Yes, faced in 1.6 beta versions
- Desktop OS/version used to run Appium: Mac El captain
- Mobile platform/version under test: iPad 2 / iOS 8.1
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI 
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

MACAMM0021:WebDriverAgent mnameit$ mkdir -p Resources/WebDriverAgent.bundle
MACAMM0021:WebDriverAgent mnameit$ sh ./Scripts/bootstrap.sh -d
-e Fetching dependencies
MACAMM0021:WebDriverAgent mnameit$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=2ad8553423bbc91a4a20cc5bda5115ecb6b000a5' test
xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
    Reason: UI Testing is not supported on “iPad” because it is running iOS 8.1 and UI Testing requires iOS 9.0 or later.
MACAMM0021:WebDriverAgent mnameit$ 

 @imurchie   : how to overcome this issue/ make WDA launched on iOS 8 devices?

Thanks,
Dilip M

**Comment by pavanbachu0604** [comment]
It is prefered to run appium 1.6 on 9.3+ devices
