### ISSUE TITLE
Precise geolocation is disabled when autoAcceptAlerts is true (real device)

### ISSUE THREAD

**Issue by jekson0702** [appium/appium-xcuitest-driver#2487]
I need to test precise geolocation in my app (real device). 
But when I enable autoAcceptAlerts "Precise geolocation" is disabled before "Allow While Using App" is clicked.

<img width="223" alt="Снимок экрана 2024-10-30 в 10 26 04" src="https://github.com/user-attachments/assets/3aa9010a-445b-4f7f-876f-c840b4d22548">

How can I avoid this? Is it a bug?

I also use acceptAlertButtonSelector setting with locator 
**/XCUIElementTypeButton[`label == "Allow While Using App"`]

appium version 2.12.0
xcuitest driver 7.28.3
Ios version 18.1

Capabilities {
appium:app: /Users/test/Desktop/app.ipa, 
appium:autoAcceptAlerts: true, 
appium:automationName: XCuiTest, 
appium:enforceAppInstall: true, 
appium:fullReset: true,
platformName: IOS
}

also tried 
capabilities.setCapability("locationServicesEnabled", true);
capabilities.setCapability("locationServicesAuthorized", true);
capabilities.setCapability("locationProvider", "gps");
capabilities.setCapability("gpsEnabled", true);
capabilities.setCapability("gpsSignalQuality", "Excellent");

Maybe part of them are for Android but it didn't help anyway

**Comment by KazuCocoa** [comment]
It is expected as current behavior, and we suggest using `acceptAlertButtonSelector` for now to configure properly for your test case.

The reason is Appium guesses the first button is the accept button in the view since XCTest itself does not provide such "accept" API. Then, what Appium could do is think the first buttons is "accept" and the last one is "deny." This works various popups but not for geolocation as the precise button.

**Comment by jekson0702** [comment]
@KazuCocoa Ok, but i've already use this setting. And alert is accepted correctly via Allow while using app. But why precise is clicked before? There are two clicks: 1 - disable precise, 2 - allow while using app.

**Comment by KazuCocoa** [comment]
Could you share the full Appium log?

**Comment by jekson0702** [comment]
yeah, but tomorrow

**Comment by jekson0702** [comment]
@KazuCocoa 
I noticed that when I'm debugging and stop execution here (after driver is created but before I can set settings)
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/86fae076-ff7a-4474-8d22-b10bd4addac4">

My app is already launched and I see geolocation permission alert. And Precise button is been switched every 2 seconds....on/off

Even if I try to set these settings through capabilities
<img width="783" alt="image" src="https://github.com/user-attachments/assets/41a2afab-db87-480a-ae8d-1f313c529a35">

I have the same result


The only way to solve this it's disable autoAccepting alerts and execute driver.switchTo().alert().accept() manually

[AppiumLog](https://gist.github.com/jekson0702/67ad4a0822e399cbd81bea772ed90cc5)

**Comment by KazuCocoa** [comment]
I see. The settings is defined to be per session, so actually the case could occur.

Then, you could start a session without `app` (nor bundleId) first, then install the app via https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-installapp and launch it via https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-launchapp
