### ISSUE TITLE
no tvOS support

### ISSUE THREAD

**Issue by sbt007** [appium/appium-xcuitest-driver#255]
There is no tvOS support even though XCTest supports it through XCode.

**Comment by imurchie** [comment]
No. There has been no demand for it, and no time to implement it. If you want to give it a shot, I can help as much as possible.

**Comment by patotskiy** [comment]
@imurchie We receive a lot of request from customers which want to automate tvOS, but I don't know ObjectiveC and cannot add support current functionality to WebDriverAgent :-)

**Comment by imurchie** [comment]
We would love to be able to support it but it is low on the priority list. If your customers want it enough, perhaps getting someone who knows Objective-C would be an option for you?
