### ISSUE TITLE
Failed to tap dynamic menu elements

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium-xcuitest-driver#257]
hi,

after resent changes in fb webdriver i have error "Failed to find scrollable visible parent with 2 visible children" with some dynamic menu elements.

**used command that generates error:** element.click();
other commands like: 
- new TouchAction((MobileDriver) driver).tap(element).perform()
- ((AppiumDriver) driver).tap(1, element, 200);
  cannot tap on these elements at all.

as workaround i am using tap by coordinates instead.

**Comment by imurchie** [comment]
@yaphatak I think this is related to your changes in WDA?

**Comment by Dheepthi** [comment]
Im facing this issue too.

org.openqa.selenium.WebDriverException: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to find scrollable visible parent with 2 visible children" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children} Command duration or timeout: 166 milliseconds Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26' System info: host: '685b35999016.ant.amazon.com', ip: '10.61.38.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111' Driver info: io.appium.java_client.ios.IOSDriver

**Comment by amedvedjev** [comment]
latest version (npm install -g appium --no-shrinkwrap):
 - element.click() - **Passed**
 - new TouchAction((MobileDriver) driver).tap(element).perform() - **Failed**
 - ((AppiumDriver) driver).tap(1, element, 200) - **Passed**


**Passed logs** (with ((AppiumDriver) driver).tap(1, element, 200)):
HTTP] --> POST /wd/hub/session/832b4a39-269e-4eff-a100-b008ec198b3c/touch/perform {"actions":[{"action":"press","options":{"element":"60117D4C-933E-4A57-BC44-7FBD0C0F7B01"}},{"action":"wait","options":{"ms":200}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"element":"60117D4C-933E-4A57-BC44-7FBD0C0F7B01"}},{"action":"wait","options":{"ms":200}},{"action":"release","options":{}}],"832b4a39-269e-4eff-a100-b008ec198b3c"]
[debug] [XCUITest] Executing command 'performTouch'

**Failed logs** (with new TouchAction((MobileDriver) driver).tap(element).perform()):
[HTTP] --> POST /wd/hub/session/f67392d1-8ded-40da-a517-93ea16573be0/touch/perform {"actions":[{"action":"tap","options":{"element":"563F7913-BF46-4C70-ADC8-87192382E0E0"}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"element":"563F7913-BF46-4C70-ADC8-87192382E0E0"}}],"f67392d1-8ded-40da-a517-93ea16573be0"]
[debug] [XCUITest] Executing command 'performTouch'

**Comment by imurchie** [comment]
Can you give a _little_ more of the failing logs? From The `[HTTP] -->` to the `[HTTP] <--` lines, for the `perform` action, at least?

**Comment by amedvedjev** [comment]
latest 1.6.1-beta [logs](https://gist.github.com/amedvedjev/121c207bdc2d078348fca1d5278d62fd)

**Comment by KBhatti** [comment]
@amedvedjev @imurchie @Dheepthi 
Could you please let me know if any of y'all figured this out? I am stuck at the same issue.

Thanks.

**Comment by Dheepthi** [comment]
I still have that failure, thats the reason i moved on to simulator XCode7.3
Please let me know if anything fixes this.

**Comment by imurchie** [comment]
This code has been pulled from the underlying system. If you update to the latest 1.6.1 beta it should not happen, I don't think.

**Comment by rbadavestewart** [comment]
@KBhatti @Dheepthi @imurchie

I can confirm that switching to the beta release solved the "Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to find scrollable visible parent with 2 visible children" problems on real devices for me.

**Comment by Dheepthi** [comment]
Thanks for your response.
I already had Appium 1.6 beta.
Can you please tell me which beta you are mentioning over here?

**Comment by jlipps** [comment]
@Dheepthi appium 1.6.1 beta

**Comment by KBhatti** [comment]
@imurchie this is for both..tapping by location or xpath, correct?
My issue was with xpath in this case.

**Comment by gysxl** [comment]
Im facing this issue too,I am on Appium 1.6.1-beta, xcode 8.0, iOS 10.1

An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to find scrollable visible parent with 2 visible children" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 688 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver

**Comment by SergeyAQA** [comment]
In my tests this issue appears when i trying to set number via numboard in iOS simulator.
