### ISSUE TITLE
Unhandled endpoint: /session//url 

### ISSUE THREAD

**Issue by Thirudhas** [appium/appium-xcuitest-driver#262]
Hi,

I am working on iOS 10 on iPhone6s. Mac OS - 10.12, while executing testcases I am getting an error. Please find below:

org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/D79CB152-02AB-455B-9824-6803AE6316CB/url -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/D79CB152-02AB-455B-9824-6803AE6316CB/url"
    );
}

Do anyone faced this issue before. Kindly help me on this

**Comment by imurchie** [comment]
We need more of the logs. 

Most likely you are in the native context, and that command does not make any sense.

**Comment by Thirudhas** [comment]
Last login: Thu Oct 27 15:32:57 on ttys001
➜  ~ appium -a "127.0.0.1" -p 4723 --platform-version "10.0" --platform-name "iOS" --app "/Users/****/Desktop/****/****.app" --session-override
^C
➜  ~ appium --address "127.0.0.1" -p 4723 --platform-version "10.0" --platform-name "iOS" --app "/Users/****/Desktop/****/****.app" --session-override -U ****** 
(node:13181) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[Appium] Welcome to Appium v1.6.0
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   sessionOverride: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0'
[Appium]   app: /Users/****/Desktop/****/****.app'
[Appium]   udid: '****'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"10.0"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/****/Desktop/****/****.app"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"*****"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0'
[Appium]   app: '/Users/****/Desktop/****/****.app'
[Appium]   udid: '*******'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/userName/Desktop/Payload/****.ipa","noReset":true,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.0","automationName":"XCUITest","udid":"*****","platformName":"iOS","deviceName":"iPhone 6","platform":"iOS","wdaLocalPort":"8100"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/userName/De...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/userName/Desktop/Payload/***.ipa'
[Appium]   noReset: true
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.0'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: '********'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'iOS'
[Appium]   wdaLocalPort: '8100'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: bab9cc80-4262-48d3-bb3e-30a0e1dad1a7
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: ***
[debug] [XCUITest] Creating iDevice object with udid ****
[XCUITest] Determining device to run tests on: udid: '*****', real device: true
[BaseDriver] Using local app '/Users/userName/Desktop/Payload/****.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[XCUITest] Error: Local zip did not exist
    at copyLocalZip$ (lib/basedriver/helpers.js:97:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Local zip did not exist
    at copyLocalZip$ (lib/basedriver/helpers.js:97:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Bad app: /Users/userName/Desktop/Payload/**.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (lib/driver.js:352:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Bad app: /Users/userName/Desktop/Payload/*****.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (lib/driver.js:352:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Reset not set, continuing
[MJSONWP] Encountered internal error running command: Error: Bad app: /Users/userName/Desktop/Payload/****.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (lib/driver.js:352:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 409 ms - 319 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/*******/Desktop/*******/*****.ipa","noReset":true,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.0","automationName":"XCUITest","udid":"*******","platformName":"iOS","deviceName":"iPhone 6","platform":"iOS","wdaLocalPort":"8100"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/******...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/*********/Desktop/********/*******.ipa'
[Appium]   noReset: true
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.0'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: '********'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'iOS'
[Appium]   wdaLocalPort: '8100'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: f5828ca4-f854-44f3-8034-20450544d77b
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: ****
[debug] [XCUITest] Creating iDevice object with udid ******
[XCUITest] Determining device to run tests on: udid: '*******', real device: true
[BaseDriver] Using local app '/Users/******/Desktop/******/******.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/9p/ss9s86yd08ld5bkln4yrg62c0000gp/T/2016928-13181-hzdee5.858e86ko6r/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/9p/ss9s86yd08ld5bkln4yrg62c0000gp/T/2016928-13181-hzdee5.858e86ko6r/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/9p/ss9s86yd08ld5bkln4yrg62c0000gp/T/2016928-13181-hzdee5.858e86ko6r/Payload/****.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [ios-app-utils] Getting bundle ID from app
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected
[....] Using iPhone 6s '****** iPhone' (********).
true

[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=*******' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/***/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D48B8794-0F01-4456-B0B3-ABD99ADD0746/Session-WebDriverAgentRunner-2016-10-28_101832-bc1gas.log
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Device: Oct 28 10:18:43 ****-iPhone XCTRunner[292] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Oct 28 10:18:44 ******-iPhone XCTRunner[292] <Notice>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Oct 28 10:18:44 ******-iPhone SpringBoard(CoreMotion)[57] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.221.41.154:8100'
[XCUITest] WebDriverAgent started at url 'http://10.221.41.154:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"AC19...
[Appium] New XCUITestDriver session created successfully, session f5828ca4-f854-44f3-8034-20450544d77b added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,...
[HTTP] <-- POST /wd/hub/session 200 29127 ms - 594 
[HTTP] --> POST /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/timeouts {"type":"implicit","ms":50}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",50,"f5828ca4-f8...
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 50ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/timeouts 200 15 ms - 76 
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: [{"id":"f5828ca4-f854-44f3-...
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 442 
[HTTP] --> GET /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["f5828ca4-f854-44f3-8034-2...
[debug] [XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/AC19CAB7-AD97-4356-8112-E1419FF64194/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"...
[MJSONWP] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" enco...
[HTTP] <-- GET /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/source 200 403 ms - 12154 
[HTTP] --> GET /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [GET /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/screenshot] to [GET http://localhost:8100/session/AC19CAB7-AD97-4356-8112-E1419FF64194/screenshot] with body: {}
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0...
[JSONWP Proxy] Replacing sessionId AC19CAB7-AD97-4356-8112-E1419FF64194 with f5828ca4-f854-44f3-8034-20450544d77b
[HTTP] <-- GET /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/screenshot 200 67 ms - 121914 
[HTTP] --> POST /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/url {"url":"/Users/*****/Desktop/*****/****.ipa"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/url] to [POST http://localhost:8100/session/AC19CAB7-AD97-4356-8112-E1419FF64194/url] with body: {"url":"/Users/***...
[JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoin...
[JSONWP Proxy] Replacing sessionId AC19CAB7-AD97-4356-8112-E1419FF64194 with f5828ca4-f854-44f3-8034-20450544d77b
[HTTP] <-- POST /wd/hub/session/f5828ca4-f854-44f3-8034-20450544d77b/url 200 17 ms - 283 
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[BaseDriver] Shutting down because we waited 60 seconds for a command
[JSONWP Proxy] Proxying [DELETE /session/f5828ca4-f854-44f3-8034-20450544d77b] to [DELETE http://localhost:8100/session/AC19CAB7-AD97-4356-8112-E1419FF64194] with no body
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session f5828ca4-f854-44f3-8034-20450544d77b from our master session list
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },...
[XCUITest] Shutting down WebDriverAgent
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
[debug] [XCUITest] Reset not set, continuing
[debug] [iOSLog] Stopping iOS log capture

**Comment by Thirudhas** [comment]
Hi @imurchie,

The above comment has my complete log of my terminal..
I am working on Native App on real device. In the console I am getting the below mentioned error.

**org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/D79CB152-02AB-455B-9824-6803AE6316CB/url -- http://localhost:8100/ with parameters {
wildcards = (
"session/D79CB152-02AB-455B-9824-6803AE6316CB/url"
);
}**

**Comment by Thirudhas** [comment]
Hi,

Find the console error while executing
org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/599894B7-DB63-4192-927A-0E5027C4D8F4/url -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/599894B7-DB63-4192-927A-0E5027C4D8F4/url"
    );
}
Command duration or timeout: 19 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '*******.local', ip: '*****', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/*****/Desktop/******/*****.ipa, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, deviceName=iPhone 6, platform=UNIX, wdaLocalPort=8100, newCommandTimeout=36000, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, platformVersion=10.0, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=deviceUDID*****, platformName=iOS}]
Session ID: 35738b6d-8545-44b6-9d34-fc4e364afae3------------------------------------------------------------------------------------------------------------------------------------

**Comment by imurchie** [comment]
Yes. You are in the native context, and there is no way to set a url. I will fix the error message.

What are you trying to do? Setting the url to  local file will do nothing, anyway.
