### ISSUE TITLE
Appium Inspector is not working 

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium-xcuitest-driver#264]
I have installed Appium 1.6 using npm. Before that I already have Appium client 1.4.13. After installing Appium 1.6 using npm I changed "Use External Appium Package" path to Appium installed through npm in "Developer Settings" in Appium 1.4.13 client. Till this I am fine.

With the Xcode 7.3, I was able to launch the 1.6 server using `appium &` from terminal and identify the elements from 1.4.13 inspector. But after installing Xcode 8 inspector is not working. What might be the issue? To automation app's using Xcode we require 1.6, but we don't have inspector with 1.6 as it is downloaded using npm. In this case 1.4.13 inspector has to work. 

@jlipps , @imurchie Please help me to get rid of this issue. This is really blocking me to add some new scripts to existing suite.

Thanks,
Shiva

**Comment by shivakrishnach31** [comment]
Hi @imurchie , Any update?

**Comment by imurchie** [comment]
The update is being worked on. In the meantime you can use https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by chenchaoyi** [comment]
Hopefully [this](https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.4lmu6wqaz) could help.

**Comment by shivakrishnach31** [comment]
Thank you @imurchie . It worked.
