### ISSUE TITLE
Add support to XCUITest driver

### ISSUE THREAD

**Issue by ericwengelking** [appium/appium-xcuitest-driver#27]
@Jonahss @jlipps 
One of our developers found a way to search for XCUIElement's using NSPredicate Strings making it a flexible way to find elements similar to what MobileBy.iOSUIAutomation() did.

What would you think if we added something like MobileBy.iOSNSPredicate() to Appium.  The pull request to Facebook's WebDriverAgent would be pretty simple, but we wanted to see if it is something you would accept in the Appium repo before we did the work.

Facebook WebDriverAgent pull request: https://github.com/facebook/WebDriverAgent/pull/124

**Comment by jlipps** [comment]
@ericwengelking yeah absolutely, we'd add a new locator strategy `-ios-nspredicate` similarly to what we've done with `-ios-uiautomation`

**Comment by jlipps** [comment]
@ericwengelking of course we'd then need to update the various clients to support it, which would take a bit of work, but i like the idea of having it for completeness

**Comment by ericwengelking** [comment]
Sounds good @jlipps , we going to focus on getting it working with the Java client first since that is what we are most familiar with then we can get it working with other clients.

**Comment by rafael-chavez** [comment]
@jlipps do you think it makes sense to backport this back to the appium-ios-driver as we are in the process of depracating? The new appium-xcuitest-driver does not use locator strategies nor does it support finding elements using NSPredicate Strings. My pull request was for the xcuitest driver https://github.com/facebook/WebDriverAgent/pull/124 (There is a XCTWebDriverAgent lib that corresponds to the xcuitest driver and a WebDriverAgentLib which corresponds to the old UIA deprecated driver).

Here is my change for the java-client: https://github.com/appium/java-client/pull/352

I was thinking we could have a separate branch (xcuitesting branch) that has this nspredicate string unless you think its a good idea to backport on the deprecating framework.

**Comment by jlipps** [comment]
I'm kind of confused, how can the new appium-xcuitest-driver not use locator strategies? It's a central part of the MJSONWP. @Jonahss maybe you can help explain this to me?

**Comment by bootstraponline** [comment]
> how can the new appium-xcuitest-driver not use locator strategies?

[it does...](https://github.com/rafael-chavez/WebDriverAgent/blob/fd496b4bfa1b4460066eabba776ed9f4666814af/XCTWebDriverAgentLib/Commands/FBFindElementCommands.m#L152)

**Comment by bootstraponline** [comment]
> do you think it makes sense to backport this back to the appium-ios-driver as we are in the process of depracating?

the point of [getElementByUIAutomation](https://github.com/appium/appium-uiauto/blob/cf5f257165c1c41c8387b2a1eb42d18915866c6a/uiauto/lib/mechanic-ext/lookup-ext.js#L132) is predicate support. I agree a new locator strategy is cleaner but it's significantly less flexible than evaling JavaScript.

**Comment by rafael-chavez** [comment]
@jlipps I dont think we are talking about the same "locator strategies". To clear this up, the strategies im talking about are in appium-ios-driver, we explicitly set these [https://github.com/appium/appium-ios-driver/blob/master/lib/driver.js#L75](strategies). appium-xcuitest-driver does not use these 'strategies'. If we want to use something like -ios-nspredicate, i would need to either map this in the appium-xcuitest-driver or change the this [https://github.com/rafael-chavez/WebDriverAgent/blob/fd496b4bfa1b4460066eabba776ed9f4666814af/XCTWebDriverAgentLib/Commands/FBFindElementCommands.m#L152](locator strategy) 
to be -ios-nspredicate instead of 'predicate string'. The latter seems cleaner to me.

@Jonahss this addition is specifically for xcuitest, where javascript is not supported anyways.

**Comment by jlipps** [comment]
@rafael-chavez yes I agree the latter strategy is preferable

**Comment by rafael-chavez** [comment]
@jlipps once [this](https://github.com/appium/appium-xcuitest-driver/pull/30) is merged, i will update the java-client pull request https://github.com/appium/java-client/pull/35 to use the '-ios predicate string' locator strategy.
