### ISSUE TITLE
XPath: Attribute values containing "UIA" are replaced with "XCUIElementType"

### ISSUE THREAD

**Issue by rjalmo** [appium/appium-xcuitest-driver#270]
Although this is intended behavior for replacing the class names in xpath locators (`UIAStaticText` -> `XCUIElementTypeStaticText`), any attribute values containing "UIA" are also replaced.

For example, the xpath locator:

```
//UIAStaticText[@name="UIA - Something"]
```

is rewritten as:

```
//XCUIElementTypeStaticText[@name="XCUIElementType - Something"]
```

rather than the expected:

```
//XCUIElementTypeStaticText[@name="UIA - Something"]
```

(this occurs for values contained in both single and double quotes)

**Comment by dpgraham** [comment]
I made some fixes to find.js in a recent commit that dealt with this (https://github.com/appium/appium-xcuitest-driver/commit/1e1aadd2425d9d2e6596a22e7eed571817b1f7d2)

I'll re-open this issue.
