### ISSUE TITLE
 xcodebuild exited with code '70' and signal 'null', while running tests on Appium 1.6 using real device

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium-xcuitest-driver#279]
Environment details.

OSX EL Captain 10.11.5
Appium 1.6.0
device iPhone 5S 
iOS 10.1.1

Attached are the Appium console log.
[Webdriver Agent.txt](https://github.com/appium/appium-xcuitest-driver/files/570672/Webdriver.Agent.txt)

**Comment by imurchie** [comment]
Can you turn on XCode logging (set the `showXcodeLog` capability to `true`), and repost the logs?

**Comment by VenkateshPS** [comment]
Attaching the log with XCode logging (set the showXcodeLog capability to true)
[showXcodeLog.txt](https://github.com/appium/appium-xcuitest-driver/files/577706/showXcodeLog.txt)

**Comment by VenkateshPS** [comment]
logs on iPhone 6 device
[showxcodelog_iphone6.txt](https://github.com/appium/appium-xcuitest-driver/files/577744/showxcodelog_iphone6.txt)

**Comment by imurchie** [comment]
In the first logs it seems that your UDID is wrong. The device it points to is not an iOS device.

In the second it seems like you're using a developer profile with a private key?

**Comment by VenkateshPS** [comment]
UDID is not wrong, I was able to run tests on the same device with Xcode 7 and Appium 1.4.13.
Problem started when dev team moved to Xcode 8 for App development, then I upgraded to Xcode 8 and Appium to 1.6.0

**Comment by imurchie** [comment]
Ok. Can you make sure the device is automatable? Open Xcode and go to Devices and make sure it is all good?

**Comment by VenkateshPS** [comment]
![screen shot 2016-11-08 at 8 52 43 am](https://cloud.githubusercontent.com/assets/11774683/20108513/1c9c0cd0-a591-11e6-93bb-3ba321080d5d.png)
Attached Xcode devices page snapshot.

**Comment by imurchie** [comment]
Ok. iOS 10.1.1 requires Xcode 8.1 (beta). Xcode 8.0 does not know what to do with it.

**Comment by VenkateshPS** [comment]
Attached is the log file after upgrading to 8.1
[showxcodelog_8_1.txt](https://github.com/appium/appium-xcuitest-driver/files/582677/showxcodelog_8_1.txt)

**Comment by imurchie** [comment]
Try capitalizing the `F` in `xcodeConfigFile`.

**Comment by VenkateshPS** [comment]
I get below error aftercapitalizing the F in xcodeConfigFile.

[Xcode] Ignoring configuration file 'Users/venkateshsingh/Desktop/vcs.xcconfig' because it could not be loaded.
	Reason: File could not be parsed due to preprocessing errors:

**Comment by VenkateshPS** [comment]
Can you please send me how to do code signing for Webdriver Project, I did code signing and now WebDriver Agent App launches on device but not the App which I am trying to Automate.

my test App is already signed with dev certificate.

Attaching the logs.
[logxcode8.txt](https://github.com/appium/appium-xcuitest-driver/files/589116/logxcode8.txt)
