### ISSUE TITLE
Issue setting up XCUITest Driver

### ISSUE THREAD

**Issue by fordarnett** [appium/appium-xcuitest-driver#28]
Hello,

I am trying to use the new XCUITest driver to see if it will help with an issue I am having running Appium with one of my apps. I have explained my situation it in detail here
[https://discuss.appium.io/t/webdriveragent-shuts-down-when-trying-to-use-appium-xcuitest-driver/9270](url)

Basically, whenever I try to run my tests with the XCUITest Driver my tests crash when I try to create a new iOSDriver. The logs of which I have included at the bottom of this post

Something I think may be causing it, I have noticed something weird going on with the current version of the WebDriverAgent in the appium-xcuitest-driver. I downloaded appium-xcuitest-driver version 1.0.1 and could not get the WebDriverAgent to even launch. However, if I used 1.0.0 I was able to get it to launch with the same error shown below. 

![image](https://cloud.githubusercontent.com/assets/17456277/14221743/dff20f06-f82e-11e5-84ca-110f8a3413a1.png)

**Comment by morphysk** [comment]
Hey, I am experiencing the same issue. Any advice how to pass it?

**Comment by imurchie** [comment]
Can you try the most recent version?
