### ISSUE TITLE
Node - Unhandled Promise rejection warnings after switching to xcuitest-driver

### ISSUE THREAD

**Issue by alexanderustwo** [appium/appium-xcuitest-driver#280]
After switching to the xcuitest-driver and running our unchanged test suite, we started getting these logs for every single scenario that we run through for iOS:

(node:53083) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 46): Error: Can't stop process; it's not currently running

Here's the appium setup I'm using:
npm list -g | grep "appium"
├─┬ appium@1.6.0
│ ├─┬ appium-android-driver@1.10.32
│ │ ├─┬ appium-adb@2.6.18
│ │ ├─┬ appium-android-bootstrap@2.7.7
│ │ │ ├─┬ appium-uiautomator@1.1.0
│ │ ├── appium-android-ime@2.0.0
│ │ ├─┬ appium-chromedriver@2.9.4
│ │ ├── appium-unlock@0.1.1
│ │ ├── io.appium.settings@2.1.0
│ ├─┬ appium-base-driver@2.0.23
│ ├─┬ appium-fake-driver@0.1.10
│ ├─┬ appium-ios-driver@1.12.31
│ │ ├─┬ appium-cookies@1.1.0
│ │ ├─┬ appium-instruments@3.8.5
│ │ ├─┬ appium-ios-log@1.2.2
│ │ ├─┬ appium-ios-simulator@1.7.13
│ │ ├─┬ appium-remote-debugger@3.1.9
│ │ │ ├── appium-atoms@0.1.0
│ │ ├─┬ appium-uiauto@2.3.3
│ │ ├─┬ appium-xcode@3.1.2
│ ├─┬ appium-logger@2.1.0
│ ├─┬ appium-selendroid-driver@1.4.3
│ ├─┬ appium-support@2.3.5
│ ├─┬ appium-uiautomator2-driver@0.0.7
│ │ ├── appium-uiautomator2-server@0.0.1
│ ├─┬ appium-windows-driver@0.2.0
│ ├─┬ appium-xcuitest-driver@2.0.34
│ ├─┬ appium-youiengine-driver@1.0.7
│ │ └─┬ appium-android-driver@1.10.31

**Comment by imurchie** [comment]
Can you provide the logs? I have not seen this happening myself.

**Comment by alexanderustwo** [comment]
@imurchie I'm very new to Appium and I'm using an already existing test suite. When I run the tests, there's not much more in the terminal logs than the Warning I posted about here, and the logging of which steps are run.

Could you please provide detailed information on how I get hold of the logs you are interested in? Are they found in some file? Do I need to provide some specific flags on execution to see them? Are there any execution flags that could prevent these logs from being displayed (which could be why I'm not seeing any more logs at the moment?)?

**Comment by imurchie** [comment]
Somewhere you run appium (probably with the `appium` command). It produces output that begins with something like:

```
[Appium] Welcome to Appium v1.6.1-beta (REV 5817d3125a8cf50f4074190dda4dbfdd60f229bd)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

That output is what is of use.

**Comment by jlipps** [comment]
FWIW I've seen a bunch of these just running our testsuite, perhaps particularly in Node v7?

**Comment by imurchie** [comment]
Hmm. Next time you see it, can you post the logs here? We should be able to track down where we are not handling things correctly.

**Comment by rkavalap** [comment]
Closing this as duplicate 
https://github.com/appium/appium/issues/7324

**Comment by jindalnaveen9** [comment]
C:\Users\Naveen>appium

[Appium] Welcome to Appium v1.17.1
(node:964) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, mk
dir 'C:\Users\Naveen\AppData\Local\Temp;C:\Program Files\Java\jre1.8.0_201\20205
5-964-9j5v20.bnl7q'
(node:964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This e
rror originated either by throwing inside of an async function without a catch b
lock, or by rejecting a promise which was not handled with .catch(). To terminat
e the node process on unhandled promise rejection, use the CLI flag `--unhandled
-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejection
s_mode). (rejection id: 1)
(node:964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprec
ated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Getting error while running through cdm
