### ISSUE TITLE
Support compiled WebDriverAgentRunner that was built by 'xcodebuild build-for-testing'

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium-xcuitest-driver#283]
Hi @imurchie 

I see `appium-xcuitest-driver` only use 'xcodebuild build test' options to build WebDriverAgent while I see Apple gives 02 for same purpose with `appium-xcuitest-driver`:
'xcodebuild build-for-testing' and 'xcodebuild test-without-building'

I see `build-for-testing` and `test-without-building` offer more convenient options which give more flexibility for `appium-xcuitest-driver`. Is there any hidden issue / decision where they're not supported yet ?

**Comment by nghiadhd** [comment]
@imurchie 

I see you already support prebuiltWDA 

https://github.com/appium/appium-xcuitest-driver/commit/0cd1b1595017e9991784321efea6f92a25ec03e7

Could you bump it up to npmjs?

**Comment by nghiadhd** [comment]
@imurchie 

Seem you are using 'xcodebuild test-without-building' & 'xcodebuild build-for-testing' wrong way

http://devstreaming.apple.com/videos/wwdc/2016/409jh83sf1h8dqrt00q/409/409_advanced_testing_and_continuous_integration.pdf

I used 'xcodebuild build-for-testing' with WebDriverAgent project, and it generates 
- WebDriverAgentRunner_iphoneos10.1-arm64.xctestrun
- Debug-iphoneos
  - WebDriverAgentLib.framework
  - WebDriverAgentRunner-Runner

and I can use 'xcodebuild test-without-building' and point to *.xctestrun to launch WebDriverAgent without WebDriverAgent.xcproject

**Comment by imurchie** [comment]
Running `xcodebuild test-without-building` on the `xcproject` works perfectly fine, after having run `xcodebuild build-for-testing`. Running them together works as well.
