### ISSUE TITLE
XCUITest doesn't pick correct simulator

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium-xcuitest-driver#293]
Have opened two simulators (iPhone 6 and iPhone 6S) using fbsimctl. When running test code with ``` noReset``` to ```true``` on iPhone 6 sim overrides iPhone 6S simulator into iPhone 6.

Running two appium session in different ports.

Logs: Server 1 : https://gist.github.com/SrinivasanTarget/f5987b02cac41c1183536c7955a35d45
Server 2: https://gist.github.com/SrinivasanTarget/858e9cc36e8bffb9773b9b0ad8bc74c0

Accept we didnt move to ```fbsimctl``` for parallel still why does ```noReset``` calls killall simulator?

@imurchie please check.

**Comment by saikrishna321** [comment]
+1

**Comment by pisarenco92** [comment]
+1

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7438](https://github.com/appium/appium/issues/7438) via [**ZenHub**](https://www.zenhub.com/)
