### ISSUE TITLE
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'

### ISSUE THREAD

**Issue by arunaousula9421** [appium/appium-xcuitest-driver#297]
Hi All, when I am try run my automation scripts I am getting above error. I have done code signing with developer settings even though I am getting the same error. 

```
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **
```

when I am running below command
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=7512a97d7339ec39286d45db3a4cbb3404baeaf9' test`
Test are passing and Webdriver agent is installed on my devices. But when I am running the automation scripts I am getting above error.

**Comment by imurchie** [comment]
Please search around the issues (open and closed). This has been discussed. You could also read the README for this repo.
