### ISSUE TITLE
Launching the test quits the WebDriverAgent

### ISSUE THREAD

**Issue by prakashsarav7** [appium/appium-xcuitest-driver#299]
Using Xcode 8.1
macOS Sierra 10.12.1
appium 1.6.0
io.appium:java-client:4.1.2

I had followed all the steps and installed the following dependencies

ideviceinstaller
libimobiledevice
ios-deploy
carthage
deviceconsole
appium-xcuitest-driver

Added automationName as XCUITest to Desired Capability

I had signed the WebDriverAgent.xcodeproj with Dev ID and able to install and run it on a real device. While running the following command `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test` , I am getting the following log

> Test Suite 'All tests' started at 2016-11-16 16:38:52.321
> Test Suite 'WebDriverAgentRunner.xctest' started at 2016-11-16 16:38:52.329
> Test Suite 'UITestingUITests' started at 2016-11-16 16:38:52.329
> Test Case '-[UITestingUITests testRunner]' started.

WebDriverAgent in launched at port 8100. Then I launch the test through script.

It installs the app on the device and tries to launch the WebDriverAgent using the following command which interrupts the already running WebDriverAgent.

> [debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=<udid>' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Waiting for WebDriverAgent to start on device

Getting this on WebDriverAgent terminal console

> ** BUILD INTERRUPTED **
> Terminated: 15

Then the test fails with following error message

> [Xcode] 2016-11-16 16:39:29.929 xcodebuild[85463:2182804] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fc37a904b80>
> 
> [Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
> Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
> 
> 
> [Xcode] 
> Testing failed:
> 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
> 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
> 
> [Xcode] ** TEST FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> [XCUITest] xcodebuild exited with code '65' and signal 'null'
> [XCUITest] Error: xcodebuild failed with code 65
>     at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
>     at emitTwo (events.js:87:13)
>     at SubProcess.emit (events.js:172:7)
>     at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
>  [Error: xcodebuild failed with code 65]
> [debug] [XCUITest] Running ios real device reset flow
> [debug] [XCUITest] Resetting simulator
> [debug] [iOSLog] Stopping iOS log capture
> [MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
>     at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
>     at emitTwo (events.js:87:13)
>     at SubProcess.emit (events.js:172:7)
>     at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by prakashsarav7** [comment]
adding this doesn't help `capabilities.setCapability("usePrebuiltWDA", true);`

**Comment by imurchie** [comment]
Appium does not provide any facility to use an already-running instance of WebDriverAgent.

**Comment by prakashsarav7** [comment]
Then the issue is with code signing of WDA by bin/run-xcodebuild.sh. I tried with xcodeconfig file with Dev id(10 chars) and Code sign identity as iPhone Developer

> DEVELOPMENT_TEAM = **********
> CODE_SIGN_IDENTITY = iPhone Developer

It says no matching iOS development profile is found. But I am able to sign, build, run it on devices manually.

**Comment by prakashsarav7** [comment]
It works for me after doing some changes in xcode configurations
