### ISSUE TITLE
How can I run tests without using Wi-Fi

### ISSUE THREAD

**Issue by estellemasso** [appium/appium-xcuitest-driver#300]
I keep getting Unable to start WebDriverAgent: Error: Unable to detect url from WebDriverAgent: http://(null):8100. Is the device on the same network as the server when there is no Wi-Fi on the device. I need to run tests without WI-Fi and ios_webkit_debug_proxy -c udid:27753 -d does not help me do this.
Please how to go about running XCUITest through USB only and no Wi-Fi

**Comment by imurchie** [comment]
You need to update Appium. This is no longer a problem.
