### ISSUE TITLE
Sometimes when app crashing it takes too long time to detect fail

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium-xcuitest-driver#305]
it takes up to 2min to got problem for appium when it tries to tap element but app was crashed before.
**Error log**:
https://gist.github.com/amedvedjev/f91394436a98125731bf3dbc699cae27

**Comment by imurchie** [comment]
Unfortunately this is Apple not getting back for that amount of time. There is not a lot that can be done about that. :(

**Comment by amedvedjev** [comment]
can we control it and stop within given timeout time?
in code we set timeout for finding elements. can we make sure that after this timeout do something if it takes longer?

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7439](https://github.com/appium/appium/issues/7439) via [**ZenHub**](https://www.zenhub.com/)
