### ISSUE TITLE
Numerous early termination of test runs on iOS 10 devices leads to "house arrest" error.

### ISSUE THREAD

**Issue by michaelgallacher** [appium/appium-xcuitest-driver#307]
## The problem
After a period of time, XCUITests will begin failing until the device is rebooted.

## Environment.
iPhone 6s on 10.2
iPad 4 on 10.2

## Details
Empirical testing shows the failure is related to the number of aborted runs done on 'older' devices.  
@Schnutzel experienced the same in #167, where an iPhone 5C fails and an iPhone SE doesn't.  

When an XCUITest is terminated before completing normally, it leaves a zombie process on the phone called `mobile_house_arrest`  After five zombies are created, iOS refuses to launch more, returning the error 

> Too many instances of this service are already running

I have never seen `mobile_house_arrest` during runs on my iPhone 6s.  It is present on every run with the iPad 4.

## Link to Appium logs
[gist](https://gist.github.com/michaelgallacher/d4224ae834eb19ff1dffd51cab59e006)

**Comment by imurchie** [comment]
Before continuing too far, can you try the latest Appium version (`npm uninstall -g appium && npm install -g appium@beta`)? There was a significant problem in how xcodebuild was being ended, which has been fixed.

**Comment by michaelgallacher** [comment]
No luck using `appium@beta`.   Aborting an iOS 10 test five times still requires a device reboot due to the zombies.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7441](https://github.com/appium/appium/issues/7441) via [**ZenHub**](https://www.zenhub.com/)
