### ISSUE TITLE
Code signing is required for product type 'UI Testing Bundle' in SdK 10.2 appium 1.6

### ISSUE THREAD

**Issue by shanky231** [appium/appium-xcuitest-driver#316]
I have installed appium 1.6 through command line and wants to test with my real device but not working, but with simulator its working.
Following error is coming
**Signing for 'WebDriverAgentRunner' requires a development team.
Code signing is required for product type 'UI Testing Bundle' in SdK 10.2
xcodebuild exited with code '0' and signal 'null'**_

I have already signed WebdriverAgentLib and Runner with my Id and i m able to build it successfully with my device through xcode.I have also tried giving the keychainPath and keychainPassword in capabilities.
My app is also signed with same Id.

Please Help. Its urgent I have a release.

One thing which i suspect is In webdriverAgentLib Provisioning profile is showing 'not required'.I have already signed it but it still not changing

**Comment by asnaith** [comment]
I had similar problems to yourself! Firstly I suggest reinstalling appium ("npm uninstall -g appium" and then "npm install -g appium@1.6.1" from the command line) to rule out any of your attempts to fix this issue causing more problems.

From a fresh install if you follow the steps below that should all that's be required to get up and running. 

a. Firstly Go to the location of the WebDriverAgent package. Open a terminal window and navigate to directory by typing: **cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent**

b. Whilst in the same directory enter the terminal command : **mkdir -p Resources/WebDriverAgent.bundle**

c. Then execute the command : **sh ./Scripts/bootstrap.sh -d**

d. Then execute the command **Open WebDriverAgent.xcodeproj** which will launch Xcode.

e.  With the "General" view selected in Xcode change the bundle identifier string on WebDriverAgentLib & IntegrationApp (replace the "facebook" part with something unique). Then with the "Build Settings" view selected in Xcode click on the WebDriverAgentRunner and scroll down to the "packaging" section and change the bundle identifier there too (replace the "facebook" part with something unique). Now that you have all the bundle identifiers set correctly, choose the "General" view again in Xcode and - choose a dev signing account for each of the following WebDriverAgentLib, WebDriverAgentRunner and IntegrationApp

f.  Start the appium server and try and run a test - it will automatically install the WebDriverAgent but it will fail the first time around as it can't launch the WebDriverAgent until the certificate for the app has been trusted on the device.
 
g. Before you try run again on the device, in iOS, go to Settings > General > Device Management and trust the certificate first

Try again after that and you should be all good!

PS I made the assumption you were sending all the correct desired capabilities to the Appium Server.

**Comment by rkavalap** [comment]
Closing as duplicate 
https://github.com/appium/appium/issues/7334
