### ISSUE TITLE
execute_script to execute UIATarget?

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#33]
This most likely isn't an issue with this driver, but figured the experts could clarify.

WIth UI Automation and Appium, we could get iOS properties from the UIATarget and adding it to the driver, like this:
`self.driver.execute_script('target=UIATarget.localTarget(); [target.name(), target.model(), target.systemName(), target.systemVersion()]')`

Do you know if there is something replaceable when using XCUITest?

**Comment by imurchie** [comment]
I do not know yet of a replacement for this. We will keep it on our radar to find something.

**Comment by imurchie** [comment]
I spoke too soon. I'd forgotten that I had added the WebDriverAgent information to the status object returned by checking the status. This will only work when a session is in progress.

Simulator:

```
{ wda:
   { state: 'success',
     os: { 
       name: 'iOS', 
       version: '10.0' 
     },
     ios: { 
       simulatorVersion: '10.0' 
     },
     build: { 
       time: 'Aug  9 2016 13:13:32' 
     } 
   } 
}
```

**Comment by joshrlesch** [comment]
oh nice, thanks for the info
