### ISSUE TITLE
Timeout unhandled endpoint.

### ISSUE THREAD

**Issue by rafael-chavez** [appium/appium-xcuitest-driver#35]
RemoteWebDriver did a refactor (here)[https://github.com/SeleniumHQ/selenium/commit/65dc17ed3435a0c4d1935e45314f4913f4e02d4e#diff-fa76272f866d8067bb11a32f27773026R817] where the timeout command changes from implicitWait to setTimeout, this breaks with XCUITest Driver. 

Options:
1. Map this in appium-xcuitest-driver to implicit wait endpoint.
2. Change remote webdriver back to using DriverCommand.IMPLICITLY_WAIT instead of DriverCommand.SET_TIMEOUT.
3. Make a pull request to try and add that endpoint to the webdriver agent, which I dont think they will accept as the old implicit endpoint is already there. (appium-xcuitest-driver uses WebDriverAgent as a dependency, not the other way around).

Ideally i would say option 1, although is there any reason why this wouldnt be an acceptable revert?
@jlipps @imurchie @Jonahss

**Comment by jlipps** [comment]
Why wouldn't (3) be a viable option given that WebDriverAgent is now apparently out of spec? As much as possible we want to avoid doing unnecessary translations in the Appium layer.

**Comment by imurchie** [comment]
I agree with at least trying to get WebDriverAgent into spec. If the pull request were complete, and it was getting them to [spec](https://w3c.github.io/webdriver/webdriver-spec.html#set-timeout).

**Comment by rafael-chavez** [comment]
Thanks for your suggestions, i made a pull request here https://github.com/facebook/WebDriverAgent/pull/151

**Comment by rafael-chavez** [comment]
Closing issue.
