### ISSUE TITLE
wd/hub/status is not implemented, returns 501 code

### ISSUE THREAD

**Issue by midopa** [appium/appium-xcuitest-driver#36]
I'm trying to connect to the XCUITest driver (commit e39444d on Node 6.1.0) through the Appium Java client (3.4.1).

Right off the bat, the driver spews out this in the console:

```
info MJSONWP Calling WebDriverAgentDriver.getStatus() with args: []
info HTTP <-- GET /wd/hub/status 501 1 ms - 88
info HTTP --> GET /wd/hub/status {}
info MJSONWP Calling WebDriverAgentDriver.getStatus() with args: []
info HTTP <-- GET /wd/hub/status 501 1 ms - 88
info HTTP --> GET /wd/hub/status {}
info MJSONWP Calling WebDriverAgentDriver.getStatus() with args: []
info HTTP <-- GET /wd/hub/status 501 1 ms - 88
info HTTP --> GET /wd/hub/status {}
```

What's happening is the Java client is pinging the server before attempting to start a session. This is reasonable behavior, I think. But it seems the driver hasn't implemented this endpoint.

**Comment by imurchie** [comment]
I've added a basic implementation to the base driver, so individual drivers will have something in this endpoint. https://github.com/appium/appium-base-driver/pull/62

**Comment by imurchie** [comment]
This is in the latest version now.
