### ISSUE TITLE
Error : An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

### ISSUE THREAD

**Issue by kalp-shah** [appium/appium-xcuitest-driver#698]
![screen shot 2018-05-11 at 3 51 21 pm](https://user-images.githubusercontent.com/38104571/39920064-5ff012f8-5533-11e8-82ce-25b3f10fcb1c.png)
## The problem

After insert desired capabilities when I start Appium server at that moment I got error "An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system."

My desired capabilities is 
{
  "platformName": "iOS",
  "platformVersion": "11.1.2",
  "deviceName": "iPhone 8",
  "app": "/Users/Desktop/iOSApp.ipa",
  "udid": "<device_udid>"
}

Previously It works and I am able to inspect element by Appium Inspector.
For Android App, It's working fine and I am able to inspect element of App by Appium inspector.
Here I attached my error message screen shot.

## Environment

- I am running Appium Desktop version _<1.6.1>_.
- I am on (pick one):
    - [ Y] Mac OS - 10.13.4
        Xcode version is :- 9.3

**Comment by kalp-shah** [comment]
@imurchie - Can you look into this issue ?

**Comment by imurchie** [comment]
Is `ios-deploy` installed and working?

**Comment by kalp-shah** [comment]
it's only working thru Sudo user. ( sudo npm install -g ios-deploy --unsafe-perm=true)
otherwise, it gives me an error.

npm install -g ios-deploy
npm WARN checkPermissions Missing write access to /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! path /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kalp/.npm/_logs/2018-06-11T13_23_33_552Z-debug.log
KalpMacs-MacBook-Pro:node_modules kalp$ npm install -g ios-deploy
npm WARN checkPermissions Missing write access to /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! path /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kalp/.npm/_logs/2018-06-11T13_24_07_571Z-debug.log
KalpMacs-MacBook-Pro:node_modules kalp$ npm install -g ios-deploy --unsafe-perm=true
npm WARN checkPermissions Missing write access to /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! path /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kalp/.npm/_logs/2018-06-11T13_24_16_330Z-debug.log
KalpMacs-MacBook-Pro:node_modules kalp$ cd ~
KalpMacs-MacBook-Pro:~ kalp$ npm install -g ios-deploy --unsafe-perm=true
npm WARN checkPermissions Missing write access to /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! path /Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/kalp/.nvm/versions/node/v6.12.0/lib/node_modules/ios-deploy' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by imurchie** [comment]
You need to give yourself permission to write to the `.nvm` directory. Probably you installed nvm with sudo. Try
```
sudo chown $(whoami): /Users/kalp/.nvm
```
Then then uninstall and reinstall ios-deploy.

**Comment by kalp-shah** [comment]
Yes. 
I uninstall node (nvm + npm) & appium and after uninstall, I install it. ( when you install at that moment, install all your dependent libraries) 
My Issue resolved.
Thanks for your help..!
