### ISSUE TITLE
Driver agent launching fails with 'RoutingHTTPServer/RoutingHTTPServer.h' file not found

### ISSUE THREAD

**Issue by rupeshbonda1985** [appium/appium-xcuitest-driver#79]
I tried to run the driver on device as per the steps provided . But I keep seeing the following error , Also attached the log and the certificate and provisional profile are set to the project . 
Let me know for more information
[Log.pdf](https://github.com/appium/appium-xcuitest-driver/files/410232/Log.pdf)

Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED **

The following build commands failed:
	CompileC /Users/gangadhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-dusrdxwfwjhxrxdzpfrhnrdhsnbi/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by pavanbachu0604** [comment]
@rupeshbonda1985 : Did you find the solution ? I am facing the same issue again

**Comment by shusso** [comment]
@pavanbachu0604 you need to run
```bash
cd appium-xcuitest-driver/WebDriverAgent
[WebDriverAgent]$ ./Scripts/bootstrap.sh
```

**Comment by pavanbachu0604** [comment]
@shusso Whats the next step ?

**Comment by imurchie** [comment]
You really should not need to manually run the bootstrap script. Appium runs it if it has not already be run. From the logs on a run with a fresh installation:

```
info XCUITest Launching WebDriverAgent on the device
dbug XCUITest Carthage found: /usr/local/bin/carthage
dbug XCUITest Running WebDriverAgent bootstrap script to install dependencies
dbug XCUITest Creating WebDriverAgent resources directory
dbug XCUITest Creating WebDriverAgent resource bundle directory
dbug XCUITest Beginning test with command 'xcodebuild -project /Users/isaac/code/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1CE361A6-5D98-44A9-A6C3-8286BCD706B1 build test' in directory '/Users/isaac/code/appium-xcuitest-driver/WebDriverAgent'
```

**Comment by imurchie** [comment]
I would re-install the xcuitest driver (by re-installing appium@beta).

**Comment by pavanbachu0604** [comment]
I am still facing the same issue, I am using the company provisioning profile do I need to add the particular bundle id to profile ?
