### ISSUE TITLE
integration with FBSimulatorControl

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#85]
Not an issue, but more of a question on if this driver will have some integrations with FBSimulatorControl? I know WebDriverAgent and it are buddy buddies, so wondering if there are plans for a capabilities setting to use it, or allow appium to use an already booted simulator?

Thanks

**Comment by imurchie** [comment]
This driver does not make use of it, no.

You should be able to use an already booted simulator, though. If you use the `udid` capability with a sim that exists, and that sim is running, it will be used and left at the end of the session.

**Comment by joshrlesch** [comment]
Yeah I was doing something like that locally at first, but trying to think how it could work with selenium grid. The node isn't picked until `webdriver.Remote()` is called, so won't know which udid use in the capabilities. 

Any ideas on a work flow like that? I have some ideas but they are pretty hacky and don't think is the best solution.
