### ISSUE TITLE
执行xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test报错

### ISSUE THREAD

**Issue by wanghuajian620** [appium/appium-xcuitest-driver#850]
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:<udid> }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:34149cb9d2cc37019164f352e21c0c9299538b9c, name:iPhone }
		{ platform:iOS Simulator, id:1969E42D-A9DF-4D09-8C99-6D8D2A1AC521, OS:12.1, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:B4F9D4BE-33CB-46A3-A178-1670166082D1, OS:12.1, name:iPad (6th generation) }
		{ platform:iOS Simulator, id:50CB4F44-76FD-40B3-90BF-A06BB2300C90, OS:12.1, name:iPad Air }
		{ platform:iOS Simulator, id:D5ED71AD-9327-444C-B4A2-92C551F24E3B, OS:12.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:072C7B60-3C0A-4147-B660-B905B013C9A2, OS:12.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:5A191EAA-E7E3-4271-A140-4A1995C10F66, OS:12.1, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:FE1C7688-BF1D-408B-B1C7-FC5E5C3869A0, OS:12.1, name:iPad Pro (11-inch) }
		{ platform:iOS Simulator, id:C6FC39E8-F4A0-45C3-8768-EE1FB68BA1E2, OS:12.1, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:5AFEFDC0-D1FF-45BD-9D82-05ACD6B076E6, OS:12.1, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:F68A413D-E499-4A1C-B101-950BD0831F9D, OS:12.1, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:C78ED168-2A6E-41F3-8AA2-D341962EDD6B, OS:12.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:C19348F1-72A9-4E93-90FC-98D8400AA445, OS:12.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:E69E00EF-610C-40F2-9823-932863C16532, OS:12.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:F1880111-4E3D-4377-8838-1FE3669990A5, OS:12.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:B0B8809E-F862-4F75-8579-05BCDB5C9D79, OS:12.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:B8154439-C985-43BB-959A-8201B3440352, OS:12.1, name:iPhone 7 }
		{ platform:iOS Simulator, id:44BC10FC-A90C-4F26-8172-AF803061BDFF, OS:12.1, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:9F66A0BA-7422-483E-BCA0-8FD56C0FDBD1, OS:12.1, name:iPhone 8 }
		{ platform:iOS Simulator, id:30FA39E8-7041-4B5E-8A45-5672EBF8321E, OS:12.1, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:39887CA9-26EF-4944-8515-AB9A3262AEC4, OS:12.1, name:iPhone SE }
		{ platform:iOS Simulator, id:DC72F2AC-C128-41B8-9C56-8A7A9EA26B54, OS:12.1, name:iPhone X }
		{ platform:iOS Simulator, id:EFCD8638-7AEF-4A7E-BF76-E5D4F536707E, OS:12.1, name:iPhone XR }
		{ platform:iOS Simulator, id:413ACB0D-E075-4EC5-A737-5BD20B383E74, OS:12.1, name:iPhone XS }
		{ platform:iOS Simulator, id:F9256F2E-C413-42A6-94AF-5AEC61D26D13, OS:12.1, name:iPhone XS Max }

	Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }`

**Comment by imurchie** [comment]
You need to provide a valid udid for a real device.

**Comment by wanghuajian620** [comment]
@imurchie Thank you!!!
