### ISSUE TITLE
Can't start WebDriverAgent when connected to company VPN

### ISSUE THREAD

**Issue by wfanforever** [appium/appium-xcuitest-driver#91]
Im seeing an issue when connected to company vpn Im not able to start the WebDriverAgent/

In /lib/webdriveragent.js, 
` this.jwproxy = new JWProxy({server: this.url.hostname, port: this.url.port, base: ''});
`
`this.url.hostname` get the the IP address instead of the localhost, that failed to start the WebDriverAgent. 

I have hard coded the server to 'localhost' to solve this issue, but there should be a better way to solve this.

**Comment by chenchaoyi** [comment]
I am observing the same on my Mac OS as well.

**Comment by imurchie** [comment]
So would adding a desired capability to set the url to whatever you'd like be a good thing?

**Comment by huminzhi** [comment]
@imurchie that sounds a good idea..

**Comment by ssynix** [comment]
When WDA runs, it logs `ServerURLHere->http://192.168.72.148:8100<-ServerURLHere`

Would it be possible to extract the URL from here?

**Comment by imurchie** [comment]
@ssynix That is what we do.

```
info XCUITest Detected that WebDriverAgent is running at url 'http://10.35.4.231:8100'
dbug WebDriverAgent Sim: Aug 25 14:44:06 isaac XCTRunner[9380]: ServerURLHere->http://10.35.4.231:8100<-ServerURLHere
info XCUITest WebDriverAgent started at url 'http://10.35.4.231:8100'
```

**Comment by rafael-chavez** [comment]
@imurchie is it safe to assume that WDA is started on the same server address as appium? if so we can just use the address parameter thats passed in as the hostName in the url. That works locally for me. 

The problem seems to be that WDA spits out the ip address for the ethernet interface, when in reality, it should be giving the uton0 interface ip.

**Comment by imurchie** [comment]
The logic around this has changed a bit. Can you try with the latest version? Thanks.

**Comment by wfanforever** [comment]
@imurchie did a quick try today, it works fine. Thanks for fixing this.

**Comment by imurchie** [comment]
Awesome!
