### ISSUE TITLE
add tests for tvOS

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-xcuitest-driver#913]
task note for xcuitest driver:

- Add unit tests in WDA
- Add functional tests for tvOS
    - I'm thinking to build and install the WDA to tvOS (and launch the preference app or install tvOS app)

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It would enough to use any of AppleTV system preinstalled apps to start

**Comment by KazuCocoa** [comment]
`com.apple.TVSettings` is in simulators by default
